const STATUS_CONFIRMED = "confirm";
const STATUS_PENDING = "pending";
const STATUS_CANCELLED = "cancelled";
const STATUS_ELIGIBLE = "eligible";
const TYPE_SABITICAL = "sabitical";

export default {
  STATUS_CONFIRMED: STATUS_CONFIRMED,
  STATUS_PENDING: STATUS_PENDING,
  STATUS_CANCELLED: STATUS_CANCELLED,
  STATUS_ELIGIBLE: STATUS_ELIGIBLE,
  TYPE_SABITICAL: TYPE_SABITICAL,
};
