export const options = [
  {
    id: "AAS-1101",
    label: "AAS-1101",
    secondaryLabel: "Imagining Asian America",
  },
  {
    id: "AAS-3211W",
    label: "AAS-3211W",
    secondaryLabel: "Race & Racism in the U.S.",
  },
  {
    id: "AAS-3251W",
    label: "AAS-3251W",
    secondaryLabel: "Race, Class, and Gender",
  },
  {
    id: "AAS-3301",
    label: "AAS-3301",
    secondaryLabel: "Asian Amer thru Arts Culture",
  },
  {
    id: "AAS-3341",
    label: "AAS-3341",
    secondaryLabel: "Asian American Images",
  },
  {
    id: "AAS-3351",
    label: "AAS-3351",
    secondaryLabel: "Asian Amer and Popular Culture",
  },
  {
    id: "AAS-3361",
    label: "AAS-3361",
    secondaryLabel: "Asian Americans and Food",
  },
  {
    id: "AAS-3601W",
    label: "AAS-3601W",
    secondaryLabel: "War & Empire: Asian Amer Persp",
  },
  {
    id: "AAS-3877",
    label: "AAS-3877",
    secondaryLabel: "Asian American History",
  },
  {
    id: "AAS-3920",
    label: "AAS-3920",
    secondaryLabel: "Topics: Asian American Studies",
  },
  { id: "AAS-3993", label: "AAS-3993", secondaryLabel: "Directed Studies" },
  {
    id: "AAS-4231",
    label: "AAS-4231",
    secondaryLabel: "Color of Public Policy in US",
  },
  { id: "AAS-5993", label: "AAS-5993", secondaryLabel: "Directed Readings" },
  { id: "ACL-5993", label: "ACL-5993", secondaryLabel: "Directed Studies" },
  {
    id: "AFRO-1009",
    label: "AFRO-1009",
    secondaryLabel: "History of Women in Africa",
  },
  { id: "AFRO-1011", label: "AFRO-1011", secondaryLabel: "Intro to Afro-Am" },
  {
    id: "AFRO-1021",
    label: "AFRO-1021",
    secondaryLabel: "Introduction to Africa",
  },
  {
    id: "AFRO-1023W",
    label: "AFRO-1023W",
    secondaryLabel: "African World Literature",
  },
  {
    id: "AFRO-1131",
    label: "AFRO-1131",
    secondaryLabel: "Contemporary Issues in Africa",
  },
  {
    id: "AFRO-1903",
    label: "AFRO-1903",
    secondaryLabel: "China-Africa Contemporary Rel",
  },
  {
    id: "AFRO-1911",
    label: "AFRO-1911",
    secondaryLabel: "Blackness and Reality TV",
  },
  {
    id: "AFRO-3006",
    label: "AFRO-3006",
    secondaryLabel: "African Migrations to Atlantic",
  },
  {
    id: "AFRO-3013",
    label: "AFRO-3013",
    secondaryLabel: "Cities and States in Africa",
  },
  {
    id: "AFRO-3015",
    label: "AFRO-3015",
    secondaryLabel: "Food Sovereignty in Africa",
  },
  {
    id: "AFRO-3016",
    label: "AFRO-3016",
    secondaryLabel: " African  Archaeology",
  },
  {
    id: "AFRO-3103",
    label: "AFRO-3103",
    secondaryLabel: "World History and Africa",
  },
  { id: "AFRO-3108", label: "AFRO-3108", secondaryLabel: "History of Jazz" },
  { id: "AFRO-3112", label: "AFRO-3112", secondaryLabel: "The Poetry of Rap" },
  {
    id: "AFRO-3120",
    label: "AFRO-3120",
    secondaryLabel: "Soc Mvts in African Diaspora",
  },
  {
    id: "AFRO-3125W",
    label: "AFRO-3125W",
    secondaryLabel: "Black Visions of Liberation",
  },
  {
    id: "AFRO-3131",
    label: "AFRO-3131",
    secondaryLabel: "Contemporary Issues in Africa",
  },
  {
    id: "AFRO-3135",
    label: "AFRO-3135",
    secondaryLabel: "Political Dynam Horn of Africa",
  },
  {
    id: "AFRO-3205",
    label: "AFRO-3205",
    secondaryLabel: "Hist of South Africa from 1910",
  },
  {
    id: "AFRO-3251W",
    label: "AFRO-3251W",
    secondaryLabel: "Race, Class & Gender",
  },
  {
    id: "AFRO-3301",
    label: "AFRO-3301",
    secondaryLabel: "Black American Music",
  },
  {
    id: "AFRO-3426",
    label: "AFRO-3426",
    secondaryLabel: "Black.Soc.Pol.&Welfare State",
  },
  {
    id: "AFRO-3431",
    label: "AFRO-3431",
    secondaryLabel: "Early Africa & Its Global Conn",
  },
  { id: "AFRO-3432", label: "AFRO-3432", secondaryLabel: "Modern Africa" },
  {
    id: "AFRO-3433",
    label: "AFRO-3433",
    secondaryLabel: "Econ Dvlpmn in Contemp Africa",
  },
  {
    id: "AFRO-3435",
    label: "AFRO-3435",
    secondaryLabel: "Political Dynam Horn of Africa",
  },
  {
    id: "AFRO-3478W",
    label: "AFRO-3478W",
    secondaryLabel: "Contemporary African Politics",
  },
  { id: "AFRO-3578", label: "AFRO-3578", secondaryLabel: "Arts of Africa" },
  {
    id: "AFRO-3592W",
    label: "AFRO-3592W",
    secondaryLabel: "Black Women Writers in the U.S",
  },
  {
    id: "AFRO-3598W",
    label: "AFRO-3598W",
    secondaryLabel: "African American Literature II",
  },
  {
    id: "AFRO-3601W",
    label: "AFRO-3601W",
    secondaryLabel: "African Literature",
  },
  {
    id: "AFRO-3625W",
    label: "AFRO-3625W",
    secondaryLabel: "Women Writers Afr/Afr Diaspora",
  },
  { id: "AFRO-3654", label: "AFRO-3654", secondaryLabel: "African Cinema" },
  {
    id: "AFRO-3745",
    label: "AFRO-3745",
    secondaryLabel: "Black Cultural Studies",
  },
  {
    id: "AFRO-3865",
    label: "AFRO-3865",
    secondaryLabel: "African Am Hist 1865 - Present",
  },
  {
    id: "AFRO-3866",
    label: "AFRO-3866",
    secondaryLabel: "Civil Rights & Black Power Mvt",
  },
  {
    id: "AFRO-3867",
    label: "AFRO-3867",
    secondaryLabel: "Black Men: Representations",
  },
  {
    id: "AFRO-3868W",
    label: "AFRO-3868W",
    secondaryLabel: "Race and War in America",
  },
  {
    id: "AFRO-3910",
    label: "AFRO-3910",
    secondaryLabel: "Topics: Afro Amer & African St",
  },
  { id: "AFRO-3993", label: "AFRO-3993", secondaryLabel: "Directed Study" },
  {
    id: "AFRO-4105",
    label: "AFRO-4105",
    secondaryLabel: "Ways of Knowing: Black Worlds",
  },
  {
    id: "AFRO-4231",
    label: "AFRO-4231",
    secondaryLabel: "Color of Public Policy in US",
  },
  { id: "AFRO-4301", label: "AFRO-4301", secondaryLabel: "African Novel" },
  { id: "AFRO-4991W", label: "AFRO-4991W", secondaryLabel: "Research Seminar" },
  {
    id: "AFRO-5015",
    label: "AFRO-5015",
    secondaryLabel: "Food Sovereignty in Africa",
  },
  {
    id: "AFRO-5016",
    label: "AFRO-5016",
    secondaryLabel: "African Archaeology",
  },
  { id: "AFRO-5101", label: "AFRO-5101", secondaryLabel: "African Diaspora" },
  {
    id: "AFRO-5625",
    label: "AFRO-5625",
    secondaryLabel: "Women Writers African Diaspora",
  },
  {
    id: "AFRO-5866",
    label: "AFRO-5866",
    secondaryLabel: "Civil Rights & Black Power Mvt",
  },
  {
    id: "AFRO-5910",
    label: "AFRO-5910",
    secondaryLabel: "Topics: Afro Amer & African St",
  },
  { id: "AFRO-5993", label: "AFRO-5993", secondaryLabel: "Directed Study" },
  { id: "AFRO-8202", label: "AFRO-8202", secondaryLabel: "History of Race" },
  {
    id: "AFRO-8590",
    label: "AFRO-8590",
    secondaryLabel: "Contemp Lit & Cultural Studies",
  },
  {
    id: "AFRO-8802",
    label: "AFRO-8802",
    secondaryLabel: "Africa & the Rise of the East",
  },
  {
    id: "AFRO-8910",
    label: "AFRO-8910",
    secondaryLabel: "Topics: Africa & African Diasp",
  },
  { id: "AFRO-8993", label: "AFRO-8993", secondaryLabel: "Directed Study" },
  { id: "AKKA-5011", label: "AKKA-5011", secondaryLabel: "Elem Akkadian I" },
  { id: "AKKA-5012", label: "AKKA-5012", secondaryLabel: "Elem Akkadian II" },
  {
    id: "AMES-1806",
    label: "AMES-1806",
    secondaryLabel: "Modern Middle Eastern Cultures",
  },
  {
    id: "AMES-8920",
    label: "AMES-8920",
    secondaryLabel: "Topics in Asian Culture",
  },
  {
    id: "AMIN-1001",
    label: "AMIN-1001",
    secondaryLabel: "Am. In. & Indigenous Peoples",
  },
  {
    id: "AMIN-1003",
    label: "AMIN-1003",
    secondaryLabel: "American Indians in MN",
  },
  { id: "AMIN-3001", label: "AMIN-3001", secondaryLabel: "Public History" },
  {
    id: "AMIN-3141",
    label: "AMIN-3141",
    secondaryLabel: "American Indian Lang. Planning",
  },
  {
    id: "AMIN-3201W",
    label: "AMIN-3201W",
    secondaryLabel: "American Indian Literature",
  },
  {
    id: "AMIN-3301",
    label: "AMIN-3301",
    secondaryLabel: "American Indian Philosophies",
  },
  {
    id: "AMIN-3312",
    label: "AMIN-3312",
    secondaryLabel: "AmIn Envl Issues/Perspectives",
  },
  {
    id: "AMIN-3602",
    label: "AMIN-3602",
    secondaryLabel: "Archaeology & Native Americans",
  },
  {
    id: "AMIN-3711",
    label: "AMIN-3711",
    secondaryLabel: "Dakota Culture & History",
  },
  {
    id: "AMIN-3871",
    label: "AMIN-3871",
    secondaryLabel: "Amer Indians to 1830",
  },
  {
    id: "AMIN-4231",
    label: "AMIN-4231",
    secondaryLabel: "Color of Public Policy in US",
  },
  {
    id: "AMIN-4501",
    label: "AMIN-4501",
    secondaryLabel: "Law, Sov'ty, & Treaty Rights",
  },
  {
    id: "AMIN-4525W",
    label: "AMIN-4525W",
    secondaryLabel: "Federal Indian Policy",
  },
  { id: "AMIN-4821W", label: "AMIN-4821W", secondaryLabel: "Capstone Seminar" },
  { id: "AMIN-4994", label: "AMIN-4994", secondaryLabel: "Directed Research" },
  {
    id: "AMIN-5141",
    label: "AMIN-5141",
    secondaryLabel: "AmIn Language Planning",
  },
  {
    id: "AMIN-5602",
    label: "AMIN-5602",
    secondaryLabel: "Archaeology & Native Americans",
  },
  {
    id: "AMIN-5920",
    label: "AMIN-5920",
    secondaryLabel: "Topics:American Indian Studies",
  },
  {
    id: "AMIN-5991",
    label: "AMIN-5991",
    secondaryLabel: "Grad Level Directed Studies",
  },
  {
    id: "AMIN-8301",
    label: "AMIN-8301",
    secondaryLabel: "Critical Indigenous Theory",
  },
  {
    id: "AMST-1012",
    label: "AMST-1012",
    secondaryLabel: "U.S. on an Immigrant Planet",
  },
  {
    id: "AMST-1101",
    label: "AMST-1101",
    secondaryLabel: "Imagining Asian America",
  },
  { id: "AMST-1511", label: "AMST-1511", secondaryLabel: "Americans Abroad" },
  {
    id: "AMST-2011",
    label: "AMST-2011",
    secondaryLabel: "U. S. since September 11th",
  },
  {
    id: "AMST-2031",
    label: "AMST-2031",
    secondaryLabel: "Chasing the American Dream",
  },
  { id: "AMST-3003", label: "AMST-3003", secondaryLabel: "Public History" },
  {
    id: "AMST-3112",
    label: "AMST-3112",
    secondaryLabel: "Prince, Porn, and Public Space",
  },
  {
    id: "AMST-3253W",
    label: "AMST-3253W",
    secondaryLabel: "Pop cult & politics",
  },
  {
    id: "AMST-3361",
    label: "AMST-3361",
    secondaryLabel: "Asian Americans and Food",
  },
  { id: "AMST-3993", label: "AMST-3993", secondaryLabel: "Directed Studies" },
  { id: "AMST-4101", label: "AMST-4101", secondaryLabel: "Gender,  Politics" },
  { id: "AMST-4962W", label: "AMST-4962W", secondaryLabel: "Proseminar II" },
  { id: "AMST-8201", label: "AMST-8201", secondaryLabel: "Hist Foundations" },
  { id: "AMST-8401", label: "AMST-8401", secondaryLabel: "Practicum" },
  {
    id: "AMST-8920",
    label: "AMST-8920",
    secondaryLabel: "Topics in American Studies",
  },
  { id: "AMST-8970", label: "AMST-8970", secondaryLabel: "Independent Study" },
  { id: "ANTH-1001", label: "ANTH-1001", secondaryLabel: "Human Evolution" },
  {
    id: "ANTH-1003V",
    label: "ANTH-1003V",
    secondaryLabel: "Understanding Cultures: Honors",
  },
  {
    id: "ANTH-1003W",
    label: "ANTH-1003W",
    secondaryLabel: "Understanding Cultures",
  },
  {
    id: "ANTH-1101",
    label: "ANTH-1101",
    secondaryLabel: "Imagining Asian America",
  },
  {
    id: "ANTH-1905",
    label: "ANTH-1905",
    secondaryLabel: "Human Evolution in Poplr Media",
  },
  {
    id: "ANTH-1911W",
    label: "ANTH-1911W",
    secondaryLabel: "Changing Human Adaptations",
  },
  {
    id: "ANTH-1914W",
    label: "ANTH-1914W",
    secondaryLabel: "American Cinema & Roots Music",
  },
  { id: "ANTH-1915", label: "ANTH-1915", secondaryLabel: "Futuristics" },
  {
    id: "ANTH-1917",
    label: "ANTH-1917",
    secondaryLabel: " Racism, Anti-Racism & America",
  },
  { id: "ANTH-1918", label: "ANTH-1918", secondaryLabel: "Justice?" },
  { id: "ANTH-2006", label: "ANTH-2006", secondaryLabel: "Humans and Aliens" },
  { id: "ANTH-3001", label: "ANTH-3001", secondaryLabel: "Intro  Archaeology" },
  {
    id: "ANTH-3002",
    label: "ANTH-3002",
    secondaryLabel: "Sex, Evolution, and Behavior",
  },
  { id: "ANTH-3003", label: "ANTH-3003", secondaryLabel: "Cultural Anth" },
  {
    id: "ANTH-3004",
    label: "ANTH-3004",
    secondaryLabel: "Controversies in Anthropology",
  },
  {
    id: "ANTH-3005W",
    label: "ANTH-3005W",
    secondaryLabel: "Language, Culture and Power",
  },
  { id: "ANTH-3006", label: "ANTH-3006", secondaryLabel: "Humans and Aliens" },
  {
    id: "ANTH-3008",
    label: "ANTH-3008",
    secondaryLabel: "Introduction to Flintknapping",
  },
  {
    id: "ANTH-3009",
    label: "ANTH-3009",
    secondaryLabel: "Pathways to Civilization",
  },
  {
    id: "ANTH-3015W",
    label: "ANTH-3015W",
    secondaryLabel: "Evolution of Language",
  },
  {
    id: "ANTH-3016",
    label: "ANTH-3016",
    secondaryLabel: "African Archaeology",
  },
  {
    id: "ANTH-3021W",
    label: "ANTH-3021W",
    secondaryLabel: "Anthropology: The Middle East",
  },
  {
    id: "ANTH-3027W",
    label: "ANTH-3027W",
    secondaryLabel: "Arch. of Prehistoric Europe",
  },
  {
    id: "ANTH-3028",
    label: "ANTH-3028",
    secondaryLabel: "Intro: Historical Archaeology",
  },
  {
    id: "ANTH-3034W",
    label: "ANTH-3034W",
    secondaryLabel: "Roots Music in America",
  },
  {
    id: "ANTH-3035",
    label: "ANTH-3035",
    secondaryLabel: "Anthropologies of Death",
  },
  {
    id: "ANTH-3036",
    label: "ANTH-3036",
    secondaryLabel: "The Body in Society",
  },
  {
    id: "ANTH-3037",
    label: "ANTH-3037",
    secondaryLabel: "Food Sovereignty in Africa",
  },
  {
    id: "ANTH-3043",
    label: "ANTH-3043",
    secondaryLabel: "Art, Aest. and Anth",
  },
  {
    id: "ANTH-3047W",
    label: "ANTH-3047W",
    secondaryLabel: "Sex, Gender & Sexuality",
  },
  {
    id: "ANTH-3049W",
    label: "ANTH-3049W",
    secondaryLabel: "Anthropology of Social Class",
  },
  {
    id: "ANTH-3145W",
    label: "ANTH-3145W",
    secondaryLabel: "Urban Anthropology",
  },
  {
    id: "ANTH-3147",
    label: "ANTH-3147",
    secondaryLabel: "Digital Anthropology",
  },
  {
    id: "ANTH-3206",
    label: "ANTH-3206",
    secondaryLabel: "Purity and Pollution",
  },
  { id: "ANTH-3221", label: "ANTH-3221", secondaryLabel: "Field School" },
  {
    id: "ANTH-3242W",
    label: "ANTH-3242W",
    secondaryLabel: "NonWestern Peoples in Movies",
  },
  {
    id: "ANTH-3255",
    label: "ANTH-3255",
    secondaryLabel: "The Archaeology of Religion",
  },
  {
    id: "ANTH-3306W",
    label: "ANTH-3306W",
    secondaryLabel: "Medical Anthropology",
  },
  {
    id: "ANTH-3310",
    label: "ANTH-3310",
    secondaryLabel: "Topics-Bio/Phys Ant",
  },
  {
    id: "ANTH-3327W",
    label: "ANTH-3327W",
    secondaryLabel: "Inca, Aztec, Maya Civilztns",
  },
  {
    id: "ANTH-3401",
    label: "ANTH-3401",
    secondaryLabel: "Human Fossil Record",
  },
  {
    id: "ANTH-3402",
    label: "ANTH-3402",
    secondaryLabel: "Zooarchaeology Laboratory",
  },
  {
    id: "ANTH-3405",
    label: "ANTH-3405",
    secondaryLabel: "Human Skeletal Analysis",
  },
  {
    id: "ANTH-3501",
    label: "ANTH-3501",
    secondaryLabel: "Managing Museum Collections",
  },
  {
    id: "ANTH-3601",
    label: "ANTH-3601",
    secondaryLabel: "Archaeology & Native Americans",
  },
  { id: "ANTH-3631", label: "ANTH-3631", secondaryLabel: "Islam in America" },
  {
    id: "ANTH-3913",
    label: "ANTH-3913",
    secondaryLabel: "Capstone Project Planning",
  },
  {
    id: "ANTH-3980",
    label: "ANTH-3980",
    secondaryLabel: "Topics in Anthropology",
  },
  {
    id: "ANTH-3993",
    label: "ANTH-3993",
    secondaryLabel: "Dir Study Capstone Proj Prep",
  },
  {
    id: "ANTH-4001",
    label: "ANTH-4001",
    secondaryLabel: "Adv Method & Theory in Arch",
  },
  {
    id: "ANTH-4002",
    label: "ANTH-4002",
    secondaryLabel: "Epidemics in Evolution",
  },
  {
    id: "ANTH-4003W",
    label: "ANTH-4003W",
    secondaryLabel: "Contmp Perspectives: Cul Anth",
  },
  {
    id: "ANTH-4004",
    label: "ANTH-4004",
    secondaryLabel: "Experimental Archaeology",
  },
  {
    id: "ANTH-4007",
    label: "ANTH-4007",
    secondaryLabel: "Lab Techniques - Archaelogy",
  },
  {
    id: "ANTH-4007H",
    label: "ANTH-4007H",
    secondaryLabel: "Lab Techniques - Archeology",
  },
  {
    id: "ANTH-4009W",
    label: "ANTH-4009W",
    secondaryLabel: "Warfare and Human Evolution",
  },
  { id: "ANTH-4013", label: "ANTH-4013", secondaryLabel: "Capstone Project" },
  { id: "ANTH-4013H", label: "ANTH-4013H", secondaryLabel: "Honors Thesis" },
  {
    id: "ANTH-4013W",
    label: "ANTH-4013W",
    secondaryLabel: "Capstone Project Writing Sem",
  },
  { id: "ANTH-4019", label: "ANTH-4019", secondaryLabel: "Symbolic Anth" },
  {
    id: "ANTH-4025",
    label: "ANTH-4025",
    secondaryLabel: "Ethnogrphc Classics",
  },
  {
    id: "ANTH-4029W",
    label: "ANTH-4029W",
    secondaryLabel: "Anthropology of Social Class",
  },
  {
    id: "ANTH-4035",
    label: "ANTH-4035",
    secondaryLabel: "Ethnog Rsrch Methds",
  },
  {
    id: "ANTH-4043",
    label: "ANTH-4043",
    secondaryLabel: "Archaeology of Northern Europe",
  },
  {
    id: "ANTH-4047",
    label: "ANTH-4047",
    secondaryLabel: "Anth of Amer Culture",
  },
  {
    id: "ANTH-4049",
    label: "ANTH-4049",
    secondaryLabel: "Religion and Culture",
  },
  {
    id: "ANTH-4053",
    label: "ANTH-4053",
    secondaryLabel: "Economic Anthropology",
  },
  { id: "ANTH-4069", label: "ANTH-4069", secondaryLabel: "Historical Ecology" },
  { id: "ANTH-4077", label: "ANTH-4077", secondaryLabel: "Neanderthals" },
  {
    id: "ANTH-4093",
    label: "ANTH-4093",
    secondaryLabel: "In-Class Capstone Project",
  },
  {
    id: "ANTH-4101",
    label: "ANTH-4101",
    secondaryLabel: "Decolonizing Archives",
  },
  {
    id: "ANTH-4121",
    label: "ANTH-4121",
    secondaryLabel: "Business Anthropology",
  },
  { id: "ANTH-4329", label: "ANTH-4329", secondaryLabel: "Primate Behavior" },
  {
    id: "ANTH-4344",
    label: "ANTH-4344",
    secondaryLabel: "Europe and its Margins",
  },
  {
    id: "ANTH-4980",
    label: "ANTH-4980",
    secondaryLabel: "Topics in Sociocultural Anth",
  },
  { id: "ANTH-4991", label: "ANTH-4991", secondaryLabel: "Independent Study" },
  { id: "ANTH-4992", label: "ANTH-4992", secondaryLabel: "Dir Readings" },
  { id: "ANTH-4993", label: "ANTH-4993", secondaryLabel: "Directed Study" },
  {
    id: "ANTH-4994W",
    label: "ANTH-4994W",
    secondaryLabel: "Directed Research",
  },
  {
    id: "ANTH-5002",
    label: "ANTH-5002",
    secondaryLabel: "Epidemics in Evolution",
  },
  {
    id: "ANTH-5008",
    label: "ANTH-5008",
    secondaryLabel: "Advanced Flintknapping",
  },
  {
    id: "ANTH-5009",
    label: "ANTH-5009",
    secondaryLabel: "Human Behavioral Biology",
  },
  {
    id: "ANTH-5015W",
    label: "ANTH-5015W",
    secondaryLabel: "Evolution of Language",
  },
  {
    id: "ANTH-5016",
    label: "ANTH-5016",
    secondaryLabel: "African Archaeology",
  },
  {
    id: "ANTH-5021W",
    label: "ANTH-5021W",
    secondaryLabel: "Anthropology:  The Middle East",
  },
  {
    id: "ANTH-5027W",
    label: "ANTH-5027W",
    secondaryLabel: "Arch. of Prehistoric Europe",
  },
  {
    id: "ANTH-5028",
    label: "ANTH-5028",
    secondaryLabel: "Intro Historical Archaeology",
  },
  {
    id: "ANTH-5037",
    label: "ANTH-5037",
    secondaryLabel: "Food Sovereignty in Africa",
  },
  {
    id: "ANTH-5045W",
    label: "ANTH-5045W",
    secondaryLabel: "Urban Anthropology",
  },
  { id: "ANTH-5112", label: "ANTH-5112", secondaryLabel: "Hominin Behavior" },
  { id: "ANTH-5113", label: "ANTH-5113", secondaryLabel: "Primate Evolution" },
  {
    id: "ANTH-5121",
    label: "ANTH-5121",
    secondaryLabel: "Business Anthropology",
  },
  {
    id: "ANTH-5128",
    label: "ANTH-5128",
    secondaryLabel: "Anthropology of Education",
  },
  {
    id: "ANTH-5221",
    label: "ANTH-5221",
    secondaryLabel: "Anthropology Material Culture",
  },
  {
    id: "ANTH-5244",
    label: "ANTH-5244",
    secondaryLabel: "Interpreting Ancient Bone",
  },
  {
    id: "ANTH-5255",
    label: "ANTH-5255",
    secondaryLabel: "The Archaeology of Religion",
  },
  {
    id: "ANTH-5269",
    label: "ANTH-5269",
    secondaryLabel: "Stone Tool Technology",
  },
  {
    id: "ANTH-5327W",
    label: "ANTH-5327W",
    secondaryLabel: "Inca, Aztec, Maya Civilztns",
  },
  {
    id: "ANTH-5401",
    label: "ANTH-5401",
    secondaryLabel: "Human Fossil Record",
  },
  {
    id: "ANTH-5402",
    label: "ANTH-5402",
    secondaryLabel: "Zooarchaeology Laboratory",
  },
  {
    id: "ANTH-5403",
    label: "ANTH-5403",
    secondaryLabel: "Quantitative Methods",
  },
  {
    id: "ANTH-5405",
    label: "ANTH-5405",
    secondaryLabel: "Human Skeletal Analysis",
  },
  {
    id: "ANTH-5442",
    label: "ANTH-5442",
    secondaryLabel: "Archaeology of  British Isles",
  },
  {
    id: "ANTH-5444",
    label: "ANTH-5444",
    secondaryLabel: "Archaeological Ceramics",
  },
  {
    id: "ANTH-5448",
    label: "ANTH-5448",
    secondaryLabel: "Applied Heritage Management",
  },
  {
    id: "ANTH-5501",
    label: "ANTH-5501",
    secondaryLabel: "Managing Museum Collections",
  },
  {
    id: "ANTH-5601",
    label: "ANTH-5601",
    secondaryLabel: "Archaeology & Native Americans",
  },
  {
    id: "ANTH-5910",
    label: "ANTH-5910",
    secondaryLabel: "Topics: Anthropology",
  },
  {
    id: "ANTH-5980",
    label: "ANTH-5980",
    secondaryLabel: "Topics in Anthropology",
  },
  {
    id: "ANTH-8001",
    label: "ANTH-8001",
    secondaryLabel: "Ethnography, Theory, History",
  },
  {
    id: "ANTH-8002",
    label: "ANTH-8002",
    secondaryLabel: "Ethno: Contemp Theory/Practice",
  },
  {
    id: "ANTH-8004",
    label: "ANTH-8004",
    secondaryLabel: "Fndtns Anth Archaeo",
  },
  {
    id: "ANTH-8009",
    label: "ANTH-8009",
    secondaryLabel: "Pathways to Civilizations",
  },
  {
    id: "ANTH-8111",
    label: "ANTH-8111",
    secondaryLabel: "Evolutionary Morphology",
  },
  { id: "ANTH-8112", label: "ANTH-8112", secondaryLabel: "Hominin Behavior" },
  { id: "ANTH-8113", label: "ANTH-8113", secondaryLabel: "Primate Evolution" },
  {
    id: "ANTH-8114",
    label: "ANTH-8114",
    secondaryLabel: "Primate Behavioral Ecology",
  },
  {
    id: "ANTH-8203",
    label: "ANTH-8203",
    secondaryLabel: "Methds/soc-cul anth",
  },
  {
    id: "ANTH-8223",
    label: "ANTH-8223",
    secondaryLabel: "Anthropology of Place & Space",
  },
  {
    id: "ANTH-8230",
    label: "ANTH-8230",
    secondaryLabel: "Anth Research Design",
  },
  {
    id: "ANTH-8244",
    label: "ANTH-8244",
    secondaryLabel: "Interpreting Ancient Bone",
  },
  {
    id: "ANTH-8310",
    label: "ANTH-8310",
    secondaryLabel: "Topics: Biological Anth",
  },
  { id: "ANTH-8333", label: "ANTH-8333", secondaryLabel: "FTE: Masters" },
  { id: "ANTH-8444", label: "ANTH-8444", secondaryLabel: "FTE: Doctoral" },
  {
    id: "ANTH-8510",
    label: "ANTH-8510",
    secondaryLabel: "Topics: Archaeology",
  },
  {
    id: "ANTH-8555",
    label: "ANTH-8555",
    secondaryLabel: "Master's Project Credits",
  },
  {
    id: "ANTH-8666",
    label: "ANTH-8666",
    secondaryLabel: "Doct Pre-Thesis Cr*",
  },
  {
    id: "ANTH-8777",
    label: "ANTH-8777",
    secondaryLabel: "Thesis Credit:Mast*",
  },
  {
    id: "ANTH-8810",
    label: "ANTH-8810",
    secondaryLabel: "Sociocultural Anthropology",
  },
  {
    id: "ANTH-8888",
    label: "ANTH-8888",
    secondaryLabel: "Thesis Credit:Doct*",
  },
  {
    id: "ANTH-8980",
    label: "ANTH-8980",
    secondaryLabel: "Anthropology Graduate Workshop",
  },
  {
    id: "ANTH-8990",
    label: "ANTH-8990",
    secondaryLabel: "Topics in Anthropology",
  },
  { id: "ANTH-8991", label: "ANTH-8991", secondaryLabel: "Independent Study" },
  { id: "ANTH-8992", label: "ANTH-8992", secondaryLabel: "Dir. Readings" },
  { id: "ANTH-8993", label: "ANTH-8993", secondaryLabel: "Directed Study" },
  { id: "ANTH-8994", label: "ANTH-8994", secondaryLabel: "Dir Research" },
  {
    id: "APEC-3061",
    label: "APEC-3061",
    secondaryLabel: "Econ Dvlpmnt in Contemp Africa",
  },
  {
    id: "ARCH-3411V",
    label: "ARCH-3411V",
    secondaryLabel: "Architectural History to 1750",
  },
  {
    id: "ARCH-3411W",
    label: "ARCH-3411W",
    secondaryLabel: "Architectural History to 1750",
  },
  { id: "ARCH-4671", label: "ARCH-4671", secondaryLabel: "Hist Prsvts" },
  { id: "ARCH-5671", label: "ARCH-5671", secondaryLabel: "Hist Prsvtn" },
  { id: "ARTH-3464", label: "ARTH-3464", secondaryLabel: "Art Since 1945" },
  {
    id: "ARTH-3896",
    label: "ARTH-3896",
    secondaryLabel: "Professional Experience",
  },
  {
    id: "ARTH-3971V",
    label: "ARTH-3971V",
    secondaryLabel: "Honors: Art History Capstone",
  },
  {
    id: "ARTH-3971W",
    label: "ARTH-3971W",
    secondaryLabel: "Art History Capstone",
  },
  {
    id: "ARTH-5787",
    label: "ARTH-5787",
    secondaryLabel: "Visual Cultures in Contact",
  },
  {
    id: "ARTH-8320",
    label: "ARTH-8320",
    secondaryLabel: "Seminar Early Mdrn Visual Cltr",
  },
  {
    id: "AST-5731",
    label: "AST-5731",
    secondaryLabel: "Bayesian Astrostatistics",
  },
  {
    id: "BIOL-1961",
    label: "BIOL-1961",
    secondaryLabel: "Foundations of Biology Lab I",
  },
  {
    id: "BIOL-3004",
    label: "BIOL-3004",
    secondaryLabel: "Foundations of Biology II Lab",
  },
  { id: "BIOL-3503", label: "BIOL-3503", secondaryLabel: "Biology of Aging" },
  {
    id: "CHIC-1102",
    label: "CHIC-1102",
    secondaryLabel: "Latinos in the United States",
  },
  {
    id: "CHIC-1102H",
    label: "CHIC-1102H",
    secondaryLabel: "Latinos in the United States",
  },
  { id: "CHIC-3352", label: "CHIC-3352", secondaryLabel: "Transborder Theory" },
  {
    id: "CHIC-3374",
    label: "CHIC-3374",
    secondaryLabel: "Migrant Farmworkers in the US",
  },
  {
    id: "CHIC-3507W",
    label: "CHIC-3507W",
    secondaryLabel: "Intro to Chicana/o literature",
  },
  {
    id: "CHIC-4231",
    label: "CHIC-4231",
    secondaryLabel: "Color of Public Policy in US",
  },
  {
    id: "CHIC-4232",
    label: "CHIC-4232",
    secondaryLabel: "Chicana Gender and Sexuality",
  },
  {
    id: "CHIC-5374",
    label: "CHIC-5374",
    secondaryLabel: "Migrant Farmworkers in the US",
  },
  { id: "CLA-3002", label: "CLA-3002", secondaryLabel: "Career Kickstarter" },
  { id: "CNES-1002", label: "CNES-1002", secondaryLabel: "World of Greece" },
  { id: "CNES-1003", label: "CNES-1003", secondaryLabel: "World of Rome" },
  {
    id: "CNES-1042",
    label: "CNES-1042",
    secondaryLabel: "Grk/Roman Mythology",
  },
  {
    id: "CNES-1042H",
    label: "CNES-1042H",
    secondaryLabel: "H: Greek and Roman Mythology",
  },
  { id: "CNES-1082", label: "CNES-1082", secondaryLabel: "Jesus in History" },
  { id: "CNES-1201", label: "CNES-1201", secondaryLabel: "Bible: Context" },
  {
    id: "CNES-1913",
    label: "CNES-1913",
    secondaryLabel: "Homer's Odyssey and Politics",
  },
  {
    id: "CNES-3061",
    label: "CNES-3061",
    secondaryLabel: "Spectacles in Antiquity",
  },
  {
    id: "CNES-3071",
    label: "CNES-3071",
    secondaryLabel: "Greek & Hellenistic Religions",
  },
  {
    id: "CNES-3074",
    label: "CNES-3074",
    secondaryLabel: "Exploring the Quran",
  },
  { id: "CNES-3076", label: "CNES-3076", secondaryLabel: "The Apostle Paul" },
  { id: "CNES-3081W", label: "CNES-3081W", secondaryLabel: "Classical Epic" },
  { id: "CNES-3082W", label: "CNES-3082W", secondaryLabel: "Greek Tragedy" },
  { id: "CNES-3092", label: "CNES-3092", secondaryLabel: "Jesus in History" },
  {
    id: "CNES-3103",
    label: "CNES-3103",
    secondaryLabel: "Ancient Greece: Alexander",
  },
  {
    id: "CNES-3106",
    label: "CNES-3106",
    secondaryLabel: "Ancient Rome: Age of Nero",
  },
  {
    id: "CNES-3201",
    label: "CNES-3201",
    secondaryLabel: "Bible:Context & Interpretation",
  },
  {
    id: "CNES-3205",
    label: "CNES-3205",
    secondaryLabel: "Women, Gender, & Hebrew Bible",
  },
  {
    id: "CNES-3206",
    label: "CNES-3206",
    secondaryLabel: "Purity and Pollution",
  },
  {
    id: "CNES-3502W",
    label: "CNES-3502W",
    secondaryLabel: "Anc Israel: Conquest to Exile",
  },
  {
    id: "CNES-3515",
    label: "CNES-3515",
    secondaryLabel: "Multiculturalism in Israel",
  },
  {
    id: "CNES-3535",
    label: "CNES-3535",
    secondaryLabel: "Death and Afterlife",
  },
  {
    id: "CNES-3601W",
    label: "CNES-3601W",
    secondaryLabel: "Sex/Gender in Greece and Rome",
  },
  {
    id: "CNES-3896",
    label: "CNES-3896",
    secondaryLabel: "Internship for Academic Credit",
  },
  { id: "CNES-3951W", label: "CNES-3951W", secondaryLabel: "Capstone" },
  { id: "CNES-3993", label: "CNES-3993", secondaryLabel: "Directed Studies" },
  {
    id: "CNES-5051",
    label: "CNES-5051",
    secondaryLabel: "Mesopotamian Historiography",
  },
  {
    id: "CNES-5071",
    label: "CNES-5071",
    secondaryLabel: "Greek & Hellenistic Religions",
  },
  {
    id: "CNES-5502W",
    label: "CNES-5502W",
    secondaryLabel: "Anc Israel: Conquest to Exile",
  },
  { id: "CNES-5713", label: "CNES-5713", secondaryLabel: "Intro: Ugaritic" },
  { id: "CNES-5993", label: "CNES-5993", secondaryLabel: "Directed Studies" },
  { id: "CNES-5994", label: "CNES-5994", secondaryLabel: "Directed Research" },
  { id: "CNES-5996", label: "CNES-5996", secondaryLabel: "Dir Instruction" },
  { id: "CNES-8333", label: "CNES-8333", secondaryLabel: "FTE: Master's" },
  { id: "CNES-8444", label: "CNES-8444", secondaryLabel: "FTE: Doctoral" },
  {
    id: "CNES-8513",
    label: "CNES-8513",
    secondaryLabel: "Scripture and Interpretation",
  },
  {
    id: "CNES-8530",
    label: "CNES-8530",
    secondaryLabel: "Ancient Mediterranean Religion",
  },
  {
    id: "CNES-8570",
    label: "CNES-8570",
    secondaryLabel: "Readings in Religious Texts",
  },
  {
    id: "CNES-8666",
    label: "CNES-8666",
    secondaryLabel: "Doct Pre-Thesis Cr*",
  },
  {
    id: "CNES-8777",
    label: "CNES-8777",
    secondaryLabel: "Thesis Credit:Mast*",
  },
  {
    id: "CNES-8888",
    label: "CNES-8888",
    secondaryLabel: "Thesis Credit:Doct*",
  },
  { id: "CNRC-1002", label: "CNRC-1002", secondaryLabel: "World of Greece" },
  { id: "CNRC-1003", label: "CNRC-1003", secondaryLabel: "World of Rome" },
  {
    id: "CNRC-1042",
    label: "CNRC-1042",
    secondaryLabel: "Grk/Roman Mythology",
  },
  {
    id: "CNRC-1042H",
    label: "CNRC-1042H",
    secondaryLabel: "H: Greek and Roman Mythology",
  },
  {
    id: "CNRC-1082",
    label: "CNRC-1082",
    secondaryLabel: "Jesus in Hist, Art & Culture",
  },
  {
    id: "CNRC-1201",
    label: "CNRC-1201",
    secondaryLabel: "Contxt & Interp, Hebrew Bible",
  },
  {
    id: "CNRC-1203",
    label: "CNRC-1203",
    secondaryLabel: "Bible: New Testament",
  },
  { id: "CNRC-1205", label: "CNRC-1205", secondaryLabel: "The Bible and Film" },
  {
    id: "CNRC-1911",
    label: "CNRC-1911",
    secondaryLabel: "Divine & Human in Hebrew Bible",
  },
  {
    id: "CNRC-1913",
    label: "CNRC-1913",
    secondaryLabel: "Homer's Odyssey & Mod Politics",
  },
  {
    id: "CNRC-1915",
    label: "CNRC-1915",
    secondaryLabel: "Ancnt/Mdern Political Violence",
  },
  {
    id: "CNRC-3016W",
    label: "CNRC-3016W",
    secondaryLabel: "Biblical Law & Jewish Ethics",
  },
  {
    id: "CNRC-3018W",
    label: "CNRC-3018W",
    secondaryLabel: "Ancient Ethics: Plato-Stoicism",
  },
  {
    id: "CNRC-3042",
    label: "CNRC-3042",
    secondaryLabel: "Myth & Lit of Anc. Near East",
  },
  {
    id: "CNRC-3061",
    label: "CNRC-3061",
    secondaryLabel: "Spectacles in Antiquity",
  },
  {
    id: "CNRC-3071",
    label: "CNRC-3071",
    secondaryLabel: "Greek & Hellenistic Religions",
  },
  {
    id: "CNRC-3074",
    label: "CNRC-3074",
    secondaryLabel: "Exploring the Quran",
  },
  { id: "CNRC-3081W", label: "CNRC-3081W", secondaryLabel: "Classical Epic" },
  { id: "CNRC-3082W", label: "CNRC-3082W", secondaryLabel: "Greek Tragedy" },
  { id: "CNRC-3092", label: "CNRC-3092", secondaryLabel: "Jesus in History" },
  {
    id: "CNRC-3102",
    label: "CNRC-3102",
    secondaryLabel: "Pompeii: Life & Death",
  },
  {
    id: "CNRC-3103",
    label: "CNRC-3103",
    secondaryLabel: "Ancient Greece: Alexander",
  },
  {
    id: "CNRC-3105",
    label: "CNRC-3105",
    secondaryLabel: "Ancient Rome: Augustus",
  },
  {
    id: "CNRC-3106",
    label: "CNRC-3106",
    secondaryLabel: "Ancient Rome: Age of Nero",
  },
  {
    id: "CNRC-3162",
    label: "CNRC-3162",
    secondaryLabel: "Roman Art and Archaeology",
  },
  {
    id: "CNRC-3201",
    label: "CNRC-3201",
    secondaryLabel: "Contxt & Interp, Hebrew Bible",
  },
  {
    id: "CNRC-3205",
    label: "CNRC-3205",
    secondaryLabel: "Women, Gender, & Hebrew Bible",
  },
  {
    id: "CNRC-3206",
    label: "CNRC-3206",
    secondaryLabel: "Purity and Pollution",
  },
  {
    id: "CNRC-3213",
    label: "CNRC-3213",
    secondaryLabel: "Bible: New Testament",
  },
  {
    id: "CNRC-3502W",
    label: "CNRC-3502W",
    secondaryLabel: "Anc Israel: Conquest to Exile",
  },
  { id: "CNRC-3506", label: "CNRC-3506", secondaryLabel: "The Israeli Mossad" },
  {
    id: "CNRC-3515",
    label: "CNRC-3515",
    secondaryLabel: "Multiculturalism in Israel",
  },
  { id: "CNRC-3518", label: "CNRC-3518", secondaryLabel: "Jewish Humor" },
  {
    id: "CNRC-3535",
    label: "CNRC-3535",
    secondaryLabel: "Death and Afterlife",
  },
  {
    id: "CNRC-3601W",
    label: "CNRC-3601W",
    secondaryLabel: "Sex/Gender in Greece and Rome",
  },
  {
    id: "CNRC-3787",
    label: "CNRC-3787",
    secondaryLabel: "Visual Cultures in Contact",
  },
  {
    id: "CNRC-3896",
    label: "CNRC-3896",
    secondaryLabel: "Internship for Academic Credit",
  },
  {
    id: "CNRC-3950",
    label: "CNRC-3950",
    secondaryLabel: "Topics: Ancient Culture",
  },
  { id: "CNRC-3993", label: "CNRC-3993", secondaryLabel: "Directed Studies" },
  {
    id: "CNRC-3994",
    label: "CNRC-3994",
    secondaryLabel: "Directed Research: Capstone",
  },
  {
    id: "CNRC-5016W",
    label: "CNRC-5016W",
    secondaryLabel: "Biblical Law & Jewish Ethics",
  },
  {
    id: "CNRC-5051",
    label: "CNRC-5051",
    secondaryLabel: "Mesopotamian Historiography",
  },
  {
    id: "CNRC-5071",
    label: "CNRC-5071",
    secondaryLabel: "Greek & Hellenistic Religions",
  },
  {
    id: "CNRC-5502W",
    label: "CNRC-5502W",
    secondaryLabel: "Anc Israel: Conquest to Exile",
  },
  {
    id: "CNRC-5787",
    label: "CNRC-5787",
    secondaryLabel: "Visual Cultures in Contact",
  },
  { id: "CNRC-5993", label: "CNRC-5993", secondaryLabel: "Directed Studies" },
  { id: "CNRC-5994", label: "CNRC-5994", secondaryLabel: "Directed Research" },
  { id: "CNRC-5996", label: "CNRC-5996", secondaryLabel: "Dir Instruction" },
  { id: "CNRC-8333", label: "CNRC-8333", secondaryLabel: "FTE: Master's" },
  { id: "CNRC-8444", label: "CNRC-8444", secondaryLabel: "FTE: Doctoral" },
  {
    id: "CNRC-8513",
    label: "CNRC-8513",
    secondaryLabel: "Scripture and Interpretation",
  },
  {
    id: "CNRC-8530",
    label: "CNRC-8530",
    secondaryLabel: "Ancient Mediterranean Religion",
  },
  {
    id: "CNRC-8570",
    label: "CNRC-8570",
    secondaryLabel: "Readings in Religious Texts",
  },
  {
    id: "CNRC-8666",
    label: "CNRC-8666",
    secondaryLabel: "Doct Pre-Thesis Cr*",
  },
  {
    id: "CNRC-8777",
    label: "CNRC-8777",
    secondaryLabel: "Thesis Credit:Mast*",
  },
  {
    id: "CNRC-8888",
    label: "CNRC-8888",
    secondaryLabel: "Thesis Credit:Doct*",
  },
  {
    id: "COMM-3341",
    label: "COMM-3341",
    secondaryLabel: "Asian American Images",
  },
  {
    id: "COMM-3351",
    label: "COMM-3351",
    secondaryLabel: "Asian Amer and Popular Culture",
  },
  {
    id: "CSCL-1001",
    label: "CSCL-1001",
    secondaryLabel: "Intro to Cultural Studies",
  },
  {
    id: "CSCL-1001W",
    label: "CSCL-1001W",
    secondaryLabel: "Intro to Cultural Studies",
  },
  { id: "CSCL-1101", label: "CSCL-1101", secondaryLabel: "Literature" },
  { id: "CSCL-1101W", label: "CSCL-1101W", secondaryLabel: "Literature" },
  {
    id: "CSCL-1201V",
    label: "CSCL-1201V",
    secondaryLabel: "Honors Course: Cinema",
  },
  { id: "CSCL-1201W", label: "CSCL-1201W", secondaryLabel: "Cinema" },
  {
    id: "CSCL-1202W",
    label: "CSCL-1202W",
    secondaryLabel: "Media: Word, Image, Sound",
  },
  { id: "CSCL-1301W", label: "CSCL-1301W", secondaryLabel: "Reading Culture" },
  {
    id: "CSCL-1401W",
    label: "CSCL-1401W",
    secondaryLabel: "Reading Literature",
  },
  { id: "CSCL-1501W", label: "CSCL-1501W", secondaryLabel: "Reading History" },
  { id: "CSCL-1914W", label: "CSCL-1914W", secondaryLabel: "What is a Poem?" },
  {
    id: "CSCL-1915",
    label: "CSCL-1915",
    secondaryLabel: "Representation in Pandemics",
  },
  { id: "CSCL-1916", label: "CSCL-1916", secondaryLabel: "The Animal" },
  {
    id: "CSCL-1917",
    label: "CSCL-1917",
    secondaryLabel: "Documenting the Present",
  },
  {
    id: "CSCL-1918",
    label: "CSCL-1918",
    secondaryLabel: "The Hollywood Musical",
  },
  { id: "CSCL-1919", label: "CSCL-1919", secondaryLabel: "Silent Cinema" },
  { id: "CSCL-1922", label: "CSCL-1922", secondaryLabel: "Films Noir" },
  { id: "CSCL-1923", label: "CSCL-1923", secondaryLabel: "Barbie™" },
  {
    id: "CSCL-1924",
    label: "CSCL-1924",
    secondaryLabel: "Doing Race in Cinema",
  },
  {
    id: "CSCL-3005",
    label: "CSCL-3005",
    secondaryLabel: "Seminar in Critical Thought",
  },
  { id: "CSCL-3111W", label: "CSCL-3111W", secondaryLabel: "Close Reading" },
  {
    id: "CSCL-3117",
    label: "CSCL-3117",
    secondaryLabel: "Concepts of Literary Study",
  },
  {
    id: "CSCL-3122",
    label: "CSCL-3122",
    secondaryLabel: "Movements and Manifestos",
  },
  {
    id: "CSCL-3130W",
    label: "CSCL-3130W",
    secondaryLabel: "Col/Postcolonial Lit & Theory",
  },
  {
    id: "CSCL-3141",
    label: "CSCL-3141",
    secondaryLabel: "Classics of World Lit",
  },
  {
    id: "CSCL-3210",
    label: "CSCL-3210",
    secondaryLabel: "Cinema and Ideology",
  },
  {
    id: "CSCL-3211",
    label: "CSCL-3211",
    secondaryLabel: "Global & Transnational Cinemas",
  },
  {
    id: "CSCL-3212W",
    label: "CSCL-3212W",
    secondaryLabel: "Documentary Cinema",
  },
  { id: "CSCL-3220W", label: "CSCL-3220W", secondaryLabel: "Screen Cultures" },
  { id: "CSCL-3221", label: "CSCL-3221", secondaryLabel: "On Television" },
  {
    id: "CSCL-3231",
    label: "CSCL-3231",
    secondaryLabel: "Comedy: Media/Politics/Society",
  },
  {
    id: "CSCL-3251",
    label: "CSCL-3251",
    secondaryLabel: "Popular Music and Mass Culture",
  },
  { id: "CSCL-3322", label: "CSCL-3322", secondaryLabel: "Visions of Nature" },
  {
    id: "CSCL-3323",
    label: "CSCL-3323",
    secondaryLabel: "Science and Culture",
  },
  {
    id: "CSCL-3334",
    label: "CSCL-3334",
    secondaryLabel: "Monsters, Robots, Cyborgs",
  },
  {
    id: "CSCL-3335",
    label: "CSCL-3335",
    secondaryLabel: "Aliens: SciFi to Social Theory",
  },
  {
    id: "CSCL-3350W",
    label: "CSCL-3350W",
    secondaryLabel: "Sexuality and Culture",
  },
  {
    id: "CSCL-3351W",
    label: "CSCL-3351W",
    secondaryLabel: "Body and Politics",
  },
  {
    id: "CSCL-3352W",
    label: "CSCL-3352W",
    secondaryLabel: "Queer Aesthetics & Critique",
  },
  { id: "CSCL-3405", label: "CSCL-3405", secondaryLabel: "Marx for Today" },
  { id: "CSCL-3412W", label: "CSCL-3412W", secondaryLabel: "Psychoanalysis" },
  {
    id: "CSCL-3425W",
    label: "CSCL-3425W",
    secondaryLabel: "Theories of Culture",
  },
  {
    id: "CSCL-3896",
    label: "CSCL-3896",
    secondaryLabel: "Internship for Academic Credit",
  },
  { id: "CSCL-3993", label: "CSCL-3993", secondaryLabel: "Directed Study" },
  { id: "CSCL-4993", label: "CSCL-4993", secondaryLabel: "Directed Study" },
  {
    id: "CSCL-5302",
    label: "CSCL-5302",
    secondaryLabel: "Aesthetics & Valuation of Art",
  },
  { id: "CSCL-5303", label: "CSCL-5303", secondaryLabel: "Sound Studies" },
  {
    id: "CSCL-5305",
    label: "CSCL-5305",
    secondaryLabel: "Vision and Visuality",
  },
  { id: "CSCL-5331", label: "CSCL-5331", secondaryLabel: "Discourse of Novel" },
  { id: "CSCL-5555", label: "CSCL-5555", secondaryLabel: "Intro to Semiotics" },
  { id: "CSCL-5666", label: "CSCL-5666", secondaryLabel: "Film Music" },
  {
    id: "CSCL-5833",
    label: "CSCL-5833",
    secondaryLabel: "Marx, Freud, Nietzsche",
  },
  {
    id: "CSCL-5910",
    label: "CSCL-5910",
    secondaryLabel: "Topics Cultrl Studies Comp Lit",
  },
  { id: "CSCL-5944H", label: "CSCL-5944H", secondaryLabel: "Honors Thesis" },
  { id: "CSCL-5993", label: "CSCL-5993", secondaryLabel: "Directed Study" },
  {
    id: "CSCL-8001",
    label: "CSCL-8001",
    secondaryLabel: "Basic Research Seminar I",
  },
  {
    id: "CSCL-8002",
    label: "CSCL-8002",
    secondaryLabel: "Basic Research Seminar 2",
  },
  {
    id: "CSCL-8888",
    label: "CSCL-8888",
    secondaryLabel: "Thesis Credit: Doctoral",
  },
  {
    id: "CSCL-8901",
    label: "CSCL-8901",
    secondaryLabel: "Introduction to the Profession",
  },
  {
    id: "CSCL-8910",
    label: "CSCL-8910",
    secondaryLabel: "Advan Topic CultrlStud/CompLit",
  },
  { id: "CSCL-8992", label: "CSCL-8992", secondaryLabel: "Directed Reading" },
  { id: "CSCL-8993", label: "CSCL-8993", secondaryLabel: "Directed Study" },
  { id: "CSCL-8994", label: "CSCL-8994", secondaryLabel: "Directed Research" },
  {
    id: "ECON-1101",
    label: "ECON-1101",
    secondaryLabel: "Principles of Microeconomics",
  },
  { id: "ECON-1102", label: "ECON-1102", secondaryLabel: "Principles Macro" },
  { id: "ECON-1165", label: "ECON-1165", secondaryLabel: "Business Economics" },
  {
    id: "ECON-3011",
    label: "ECON-3011",
    secondaryLabel: "Intermediate Microeconomics I",
  },
  {
    id: "ECON-3012",
    label: "ECON-3012",
    secondaryLabel: "Intermediate Microeconomics II",
  },
  {
    id: "ECON-3023",
    label: "ECON-3023",
    secondaryLabel: "Intermediate Macroeconomics I",
  },
  {
    id: "ECON-3024",
    label: "ECON-3024",
    secondaryLabel: "Intermediate Macroeconomics II",
  },
  {
    id: "ECON-3101",
    label: "ECON-3101",
    secondaryLabel: "Intermediate Microeconomics",
  },
  {
    id: "ECON-3102",
    label: "ECON-3102",
    secondaryLabel: "Intermediate Macroeconomics",
  },
  {
    id: "ECON-3896",
    label: "ECON-3896",
    secondaryLabel: "Internship for Academic Credit",
  },
  { id: "ECON-3951", label: "ECON-3951", secondaryLabel: "Economics Capstone" },
  {
    id: "ECON-3960",
    label: "ECON-3960",
    secondaryLabel: "Topics in Economics",
  },
  { id: "ECON-3991", label: "ECON-3991", secondaryLabel: "Independent Study" },
  { id: "ECON-3993", label: "ECON-3993", secondaryLabel: "Directed Studies" },
  {
    id: "ECON-4115",
    label: "ECON-4115",
    secondaryLabel: "Uncertainty and Information",
  },
  {
    id: "ECON-4118",
    label: "ECON-4118",
    secondaryLabel: "Advanced Mathematical Econ",
  },
  {
    id: "ECON-4161",
    label: "ECON-4161",
    secondaryLabel: "Microeconomic Analysis I",
  },
  {
    id: "ECON-4162",
    label: "ECON-4162",
    secondaryLabel: "Microeconomic Analysis II",
  },
  {
    id: "ECON-4163",
    label: "ECON-4163",
    secondaryLabel: "Microecon Analysis III",
  },
  {
    id: "ECON-4164",
    label: "ECON-4164",
    secondaryLabel: "Microecon Analysis IV",
  },
  { id: "ECON-4165", label: "ECON-4165", secondaryLabel: "Macroecon Theory" },
  { id: "ECON-4166", label: "ECON-4166", secondaryLabel: "Macroecon Theory" },
  { id: "ECON-4167", label: "ECON-4167", secondaryLabel: "Macroecon Theory" },
  { id: "ECON-4168", label: "ECON-4168", secondaryLabel: "Macroecon Theory" },
  {
    id: "ECON-4211",
    label: "ECON-4211",
    secondaryLabel: "Principles of Econometrics",
  },
  {
    id: "ECON-4261",
    label: "ECON-4261",
    secondaryLabel: "Introduction to Econometrics",
  },
  {
    id: "ECON-4311",
    label: "ECON-4311",
    secondaryLabel: "Economy of Latin America",
  },
  {
    id: "ECON-4317",
    label: "ECON-4317",
    secondaryLabel: "The Chinese Economy",
  },
  {
    id: "ECON-4331W",
    label: "ECON-4331W",
    secondaryLabel: "Economic Development",
  },
  {
    id: "ECON-4341",
    label: "ECON-4341",
    secondaryLabel: "Poverty and Income Inequality",
  },
  {
    id: "ECON-4341W",
    label: "ECON-4341W",
    secondaryLabel: "Poverty and Income Inequality",
  },
  {
    id: "ECON-4428",
    label: "ECON-4428",
    secondaryLabel: "London Trade and Brexit",
  },
  {
    id: "ECON-4431W",
    label: "ECON-4431W",
    secondaryLabel: "International Trade",
  },
  {
    id: "ECON-4432",
    label: "ECON-4432",
    secondaryLabel: "International Finance",
  },
  {
    id: "ECON-4432W",
    label: "ECON-4432W",
    secondaryLabel: "International Finance",
  },
  {
    id: "ECON-4438W",
    label: "ECON-4438W",
    secondaryLabel: "Advanced International Trade",
  },
  { id: "ECON-4531", label: "ECON-4531", secondaryLabel: "Labor Economics" },
  {
    id: "ECON-4538",
    label: "ECON-4538",
    secondaryLabel: "Advanced Labor Economics",
  },
  {
    id: "ECON-4631",
    label: "ECON-4631",
    secondaryLabel: "Industrial Organization",
  },
  { id: "ECON-4721", label: "ECON-4721", secondaryLabel: "Money and Banking" },
  {
    id: "ECON-4751",
    label: "ECON-4751",
    secondaryLabel: "Financial Economics",
  },
  {
    id: "ECON-4758",
    label: "ECON-4758",
    secondaryLabel: "Advanced Financial Economics",
  },
  { id: "ECON-4821", label: "ECON-4821", secondaryLabel: "Public Economics" },
  {
    id: "ECON-4831",
    label: "ECON-4831",
    secondaryLabel: "Cost-Benefit Analysis",
  },
  {
    id: "ECON-4960",
    label: "ECON-4960",
    secondaryLabel: "Topics in Economics",
  },
  { id: "ECON-4993", label: "ECON-4993", secondaryLabel: "Directed Study" },
  { id: "ECON-8101", label: "ECON-8101", secondaryLabel: "Microecon Theory" },
  { id: "ECON-8102", label: "ECON-8102", secondaryLabel: "Microecon Theory" },
  { id: "ECON-8103", label: "ECON-8103", secondaryLabel: "Microecon Theory" },
  { id: "ECON-8104", label: "ECON-8104", secondaryLabel: "Microecon Theory" },
  { id: "ECON-8105", label: "ECON-8105", secondaryLabel: "Macroecon Theory" },
  { id: "ECON-8106", label: "ECON-8106", secondaryLabel: "Macroecon Theory" },
  { id: "ECON-8107", label: "ECON-8107", secondaryLabel: "Macroecon Theory" },
  { id: "ECON-8108", label: "ECON-8108", secondaryLabel: "Macroecon Theory" },
  {
    id: "ECON-8117",
    label: "ECON-8117",
    secondaryLabel: "Noncoop Game Theory",
  },
  {
    id: "ECON-8118",
    label: "ECON-8118",
    secondaryLabel: "Noncoop Game Theory",
  },
  { id: "ECON-8181", label: "ECON-8181", secondaryLabel: "Advanced Microecon" },
  { id: "ECON-8182", label: "ECON-8182", secondaryLabel: "Advanced Microecon" },
  { id: "ECON-8185", label: "ECON-8185", secondaryLabel: "Advanced Macroecon" },
  {
    id: "ECON-8186",
    label: "ECON-8186",
    secondaryLabel: "Adv Topics in Macroeconomics",
  },
  { id: "ECON-8191", label: "ECON-8191", secondaryLabel: "Workshop Math Econ" },
  { id: "ECON-8192", label: "ECON-8192", secondaryLabel: "Workshop Math Econ" },
  { id: "ECON-8205", label: "ECON-8205", secondaryLabel: "Appl Econometrics" },
  { id: "ECON-8206", label: "ECON-8206", secondaryLabel: "Appl Econometrics" },
  { id: "ECON-8207", label: "ECON-8207", secondaryLabel: "Appl Econometrics" },
  { id: "ECON-8208", label: "ECON-8208", secondaryLabel: "Appl Econometrics" },
  { id: "ECON-8311", label: "ECON-8311", secondaryLabel: "Econ Growth/Dev" },
  { id: "ECON-8312", label: "ECON-8312", secondaryLabel: "Econ Growth/Dev" },
  { id: "ECON-8313", label: "ECON-8313", secondaryLabel: "Econ Growth/Dev" },
  { id: "ECON-8391", label: "ECON-8391", secondaryLabel: "Wkshop Growth/Dev" },
  { id: "ECON-8392", label: "ECON-8392", secondaryLabel: "Wkshop Growth/Dev" },
  {
    id: "ECON-8401",
    label: "ECON-8401",
    secondaryLabel: "Intl Trade/Payments",
  },
  {
    id: "ECON-8402",
    label: "ECON-8402",
    secondaryLabel: "Intl Trade/Payments",
  },
  {
    id: "ECON-8403",
    label: "ECON-8403",
    secondaryLabel: "Intl Trade/Payments",
  },
  { id: "ECON-8491", label: "ECON-8491", secondaryLabel: "Wkshop Trade/Dev" },
  { id: "ECON-8492", label: "ECON-8492", secondaryLabel: "Wkshop Trade/Dev" },
  { id: "ECON-8501", label: "ECON-8501", secondaryLabel: "Wages & Employment" },
  {
    id: "ECON-8502",
    label: "ECON-8502",
    secondaryLabel: "Wages and Employment",
  },
  { id: "ECON-8503", label: "ECON-8503", secondaryLabel: "Wages & Employment" },
  { id: "ECON-8581", label: "ECON-8581", secondaryLabel: "Adv Labor Econ" },
  { id: "ECON-8582", label: "ECON-8582", secondaryLabel: "Adv Labor Econ" },
  { id: "ECON-8601", label: "ECON-8601", secondaryLabel: "Industrial Org" },
  { id: "ECON-8602", label: "ECON-8602", secondaryLabel: "Industrial Org" },
  { id: "ECON-8603", label: "ECON-8603", secondaryLabel: "Industrial Org" },
  { id: "ECON-8691", label: "ECON-8691", secondaryLabel: "Wkshop Appl Micro" },
  { id: "ECON-8692", label: "ECON-8692", secondaryLabel: "Wkshop Appl Micro" },
  { id: "ECON-8701", label: "ECON-8701", secondaryLabel: "Monetary Economics" },
  { id: "ECON-8702", label: "ECON-8702", secondaryLabel: "Monetary Economics" },
  { id: "ECON-8704", label: "ECON-8704", secondaryLabel: "Financial Econ" },
  { id: "ECON-8705", label: "ECON-8705", secondaryLabel: "Financial Econ" },
  { id: "ECON-8791", label: "ECON-8791", secondaryLabel: "Workshop Macro" },
  { id: "ECON-8792", label: "ECON-8792", secondaryLabel: "Workshop Macro" },
  { id: "ECON-8801", label: "ECON-8801", secondaryLabel: "Public Economics" },
  { id: "ECON-8802", label: "ECON-8802", secondaryLabel: "Public Economics" },
  { id: "ECON-8803", label: "ECON-8803", secondaryLabel: "Public Econ" },
  { id: "ECON-8891", label: "ECON-8891", secondaryLabel: "Workshop Public" },
  { id: "ECON-8892", label: "ECON-8892", secondaryLabel: "Workshop Public" },
  {
    id: "ECON-8990",
    label: "ECON-8990",
    secondaryLabel: "Indiv Grad Research",
  },
  {
    id: "EEB-3002",
    label: "EEB-3002",
    secondaryLabel: "Sex, Evolution, and Behavior",
  },
  { id: "EEB-3407", label: "EEB-3407", secondaryLabel: "Ecology" },
  { id: "EEB-3409", label: "EEB-3409", secondaryLabel: "Evolution" },
  {
    id: "EEB-3412W",
    label: "EEB-3412W",
    secondaryLabel: "Intro to Animal Behavior",
  },
  {
    id: "EEB-4134",
    label: "EEB-4134",
    secondaryLabel: "Introduction to Ornithology",
  },
  { id: "EEB-4329", label: "EEB-4329", secondaryLabel: "Primate Behavior" },
  {
    id: "EEB-4793W",
    label: "EEB-4793W",
    secondaryLabel: "Directed Studies: WI",
  },
  {
    id: "EEB-4794W",
    label: "EEB-4794W",
    secondaryLabel: "Directed Research: WI",
  },
  { id: "EEB-4993", label: "EEB-4993", secondaryLabel: "Directed Studies" },
  { id: "EEB-4994", label: "EEB-4994", secondaryLabel: "Directed Research" },
  { id: "EEB-5407", label: "EEB-5407", secondaryLabel: "Ecology" },
  { id: "EEB-5409", label: "EEB-5409", secondaryLabel: "Evolution" },
  { id: "EEB-8991", label: "EEB-8991", secondaryLabel: "I S Eco Evol Behavr" },
  { id: "EEB-8994", label: "EEB-8994", secondaryLabel: "Directed Research" },
  {
    id: "EMS-5500",
    label: "EMS-5500",
    secondaryLabel: "Topics in Early Modern Studies",
  },
  {
    id: "EMS-8100",
    label: "EMS-8100",
    secondaryLabel: "Workshop: Early Modern Studies",
  },
  {
    id: "EMS-8250",
    label: "EMS-8250",
    secondaryLabel: "Sem in Early Modern Studies",
  },
  {
    id: "EMS-8500",
    label: "EMS-8500",
    secondaryLabel: "Topics in Early Modern Studies",
  },
  {
    id: "ENGL-3025",
    label: "ENGL-3025",
    secondaryLabel: "The End of the World",
  },
  {
    id: "ENGL-3507W",
    label: "ENGL-3507W",
    secondaryLabel: "Intro to Chicana/o Literature",
  },
  {
    id: "ENGL-3592W",
    label: "ENGL-3592W",
    secondaryLabel: "Black Women Writers in the US",
  },
  {
    id: "ENGL-3598W",
    label: "ENGL-3598W",
    secondaryLabel: "African American Literature II",
  },
  {
    id: "ENGL-8520",
    label: "ENGL-8520",
    secondaryLabel: "Seminar in Adv Cltl Thry Prctc",
  },
  {
    id: "FRIT-1601",
    label: "FRIT-1601",
    secondaryLabel: "Migrants/Refugees in Film",
  },
  { id: "GCC-3037", label: "GCC-3037", secondaryLabel: "Wealth & Inequality" },
  {
    id: "GEOG-1301W",
    label: "GEOG-1301W",
    secondaryLabel: "Our Globalizing World",
  },
  { id: "GEOG-1502", label: "GEOG-1502", secondaryLabel: "Mapping Our World" },
  {
    id: "GEOG-3371W",
    label: "GEOG-3371W",
    secondaryLabel: "Cities, Citizens & Communities",
  },
  {
    id: "GEOG-3411W",
    label: "GEOG-3411W",
    secondaryLabel: "Geog of Health & Health Care",
  },
  {
    id: "GLBT-3456W",
    label: "GLBT-3456W",
    secondaryLabel: "Sexuality and Culture",
  },
  { id: "GLBT-4101", label: "GLBT-4101", secondaryLabel: "Gender, Politics" },
  {
    id: "GLOS-1105",
    label: "GLOS-1105",
    secondaryLabel: "Climate Crisis-Climate Justice",
  },
  {
    id: "GLOS-1112",
    label: "GLOS-1112",
    secondaryLabel: "Social Justice & Globalization",
  },
  { id: "GLOS-1916", label: "GLOS-1916", secondaryLabel: "Do the Right Thing" },
  {
    id: "GLOS-1917",
    label: "GLOS-1917",
    secondaryLabel: "The Politics of Non-violence",
  },
  {
    id: "GLOS-1918",
    label: "GLOS-1918",
    secondaryLabel: "A Changing Climate and You",
  },
  {
    id: "GLOS-3105",
    label: "GLOS-3105",
    secondaryLabel: "Ways of Knowing Global Studies",
  },
  {
    id: "GLOS-3105H",
    label: "GLOS-3105H",
    secondaryLabel: "Honors: Exploring the World",
  },
  {
    id: "GLOS-3143",
    label: "GLOS-3143",
    secondaryLabel: "Living in the Global",
  },
  {
    id: "GLOS-3144",
    label: "GLOS-3144",
    secondaryLabel: "Knowledge and Power",
  },
  {
    id: "GLOS-3144H",
    label: "GLOS-3144H",
    secondaryLabel: "Honors: Knowledge and Power",
  },
  {
    id: "GLOS-3145",
    label: "GLOS-3145",
    secondaryLabel: "Global Mod, Nat-State, Capital",
  },
  {
    id: "GLOS-3145H",
    label: "GLOS-3145H",
    secondaryLabel: "Honors: Mod, Nat-State, Captl",
  },
  {
    id: "GLOS-3215",
    label: "GLOS-3215",
    secondaryLabel: "Supercapitalism Global Economy",
  },
  {
    id: "GLOS-3225",
    label: "GLOS-3225",
    secondaryLabel: "The Power of the 1%",
  },
  {
    id: "GLOS-3305",
    label: "GLOS-3305",
    secondaryLabel: "Life for Sale: Global Debates",
  },
  {
    id: "GLOS-3401W",
    label: "GLOS-3401W",
    secondaryLabel: "International Human Rights Law",
  },
  {
    id: "GLOS-3404",
    label: "GLOS-3404",
    secondaryLabel: "More Than Human Rights",
  },
  {
    id: "GLOS-3407",
    label: "GLOS-3407",
    secondaryLabel: "Global Islamophobia",
  },
  { id: "GLOS-3412", label: "GLOS-3412", secondaryLabel: "What is Equality?" },
  {
    id: "GLOS-3415W",
    label: "GLOS-3415W",
    secondaryLabel: "Global Institutions of Power",
  },
  {
    id: "GLOS-3550V",
    label: "GLOS-3550V",
    secondaryLabel: "Honors Course: Sup Res Paper",
  },
  { id: "GLOS-3602", label: "GLOS-3602", secondaryLabel: "In Other Worlds" },
  {
    id: "GLOS-3606",
    label: "GLOS-3606",
    secondaryLabel: "Art and Incarceration",
  },
  { id: "GLOS-3609", label: "GLOS-3609", secondaryLabel: "Novels and Nations" },
  {
    id: "GLOS-3611",
    label: "GLOS-3611",
    secondaryLabel: "Stories, Bodies, Movements",
  },
  {
    id: "GLOS-3613W",
    label: "GLOS-3613W",
    secondaryLabel: "The Politics of Eating",
  },
  {
    id: "GLOS-3681",
    label: "GLOS-3681",
    secondaryLabel: "Gender in the Islamic World",
  },
  {
    id: "GLOS-3705",
    label: "GLOS-3705",
    secondaryLabel: "Migrations: People in Motion",
  },
  {
    id: "GLOS-3706",
    label: "GLOS-3706",
    secondaryLabel: "Criminalization of Migration",
  },
  {
    id: "GLOS-3707",
    label: "GLOS-3707",
    secondaryLabel: "Surplus Value/Surplus Humanity",
  },
  {
    id: "GLOS-3896",
    label: "GLOS-3896",
    secondaryLabel: "Global Studies Internship",
  },
  {
    id: "GLOS-3900",
    label: "GLOS-3900",
    secondaryLabel: "Topics: Global Studies",
  },
  { id: "GLOS-3981W", label: "GLOS-3981W", secondaryLabel: "Major Project" },
  {
    id: "GLOS-3985V",
    label: "GLOS-3985V",
    secondaryLabel: "Honors Capstone Seminar",
  },
  { id: "GLOS-3993", label: "GLOS-3993", secondaryLabel: "Directed Study" },
  { id: "GLOS-4221", label: "GLOS-4221", secondaryLabel: "Globalize This!" },
  {
    id: "GLOS-4311",
    label: "GLOS-4311",
    secondaryLabel: "Power, Justice & Environment",
  },
  {
    id: "GLOS-4344",
    label: "GLOS-4344",
    secondaryLabel: "Europe and its Margins",
  },
  {
    id: "GLOS-5403",
    label: "GLOS-5403",
    secondaryLabel: "Human Rights Advocacy",
  },
  {
    id: "GLOS-5500",
    label: "GLOS-5500",
    secondaryLabel: "Graduate Topic: Global Studies",
  },
  {
    id: "GLOS-5611",
    label: "GLOS-5611",
    secondaryLabel: "Stories, Bodies, Movements",
  },
  {
    id: "GLOS-5900",
    label: "GLOS-5900",
    secondaryLabel: "Topics: Global Studies",
  },
  { id: "GLOS-5993", label: "GLOS-5993", secondaryLabel: "Directed Studies" },
  { id: "GLOS-5994", label: "GLOS-5994", secondaryLabel: "Directed Research" },
  { id: "GRAD-8401", label: "GRAD-8401", secondaryLabel: "DPD Seminar" },
  { id: "GRK-1001", label: "GRK-1001", secondaryLabel: "Beg. Class. Grk. I" },
  { id: "GRK-1002", label: "GRK-1002", secondaryLabel: "Beg. Class. Grk. II" },
  {
    id: "GRK-3003",
    label: "GRK-3003",
    secondaryLabel: "Intermediate Greek Prose",
  },
  {
    id: "GRK-3004",
    label: "GRK-3004",
    secondaryLabel: "Intermediate Greek Poetry",
  },
  { id: "GRK-3993", label: "GRK-3993", secondaryLabel: "Directed Studies" },
  {
    id: "GRK-5003",
    label: "GRK-5003",
    secondaryLabel: "Int Greek Prose: Grad Research",
  },
  {
    id: "GRK-5004",
    label: "GRK-5004",
    secondaryLabel: "Int Greek Poetry Grad Research",
  },
  { id: "GRK-5100", label: "GRK-5100", secondaryLabel: "Advanced Reading" },
  { id: "GRK-5200", label: "GRK-5200", secondaryLabel: "Biblical Greek" },
  { id: "GRK-5701", label: "GRK-5701", secondaryLabel: "Prose Comp." },
  { id: "GRK-5993", label: "GRK-5993", secondaryLabel: "Directed Studies" },
  {
    id: "GRK-8100",
    label: "GRK-8100",
    secondaryLabel: "Readings in Greek Prose",
  },
  { id: "GRK-8910", label: "GRK-8910", secondaryLabel: "Seminar" },
  { id: "GWSS-1002", label: "GWSS-1002", secondaryLabel: "Politics of Sex" },
  {
    id: "GWSS-1006",
    label: "GWSS-1006",
    secondaryLabel: "Skin, Sex, and Genes",
  },
  {
    id: "GWSS-3203W",
    label: "GWSS-3203W",
    secondaryLabel: "Blood, Bodies and Science",
  },
  {
    id: "GWSS-3215",
    label: "GWSS-3215",
    secondaryLabel: "Bod That Mtr: Fem Disabi Stud",
  },
  {
    id: "GWSS-3218",
    label: "GWSS-3218",
    secondaryLabel: "Politics of Reproduction",
  },
  {
    id: "GWSS-3406",
    label: "GWSS-3406",
    secondaryLabel: "Gender, Labor, and Politics",
  },
  {
    id: "GWSS-3406H",
    label: "GWSS-3406H",
    secondaryLabel: "Honors: Gender, Work, Labor",
  },
  {
    id: "GWSS-3611",
    label: "GWSS-3611",
    secondaryLabel: "Stories, Bodies, Movements",
  },
  {
    id: "GWSS-3626W",
    label: "GWSS-3626W",
    secondaryLabel: "Witches, Seers and Saints",
  },
  {
    id: "GWSS-3681",
    label: "GWSS-3681",
    secondaryLabel: "Gender in the Islamic World",
  },
  {
    id: "GWSS-4002",
    label: "GWSS-4002",
    secondaryLabel: "Politics of Engagement",
  },
  {
    id: "GWSS-4590",
    label: "GWSS-4590",
    secondaryLabel: "Topics: Change/Activism/Policy",
  },
  {
    id: "HCOL-3101H",
    label: "HCOL-3101H",
    secondaryLabel: "Honors Thesis - Development",
  },
  {
    id: "HCOL-3102H",
    label: "HCOL-3102H",
    secondaryLabel: "Honors Thesis - Writing",
  },
  { id: "HEBR-1001", label: "HEBR-1001", secondaryLabel: "Beginning Hebrew I" },
  {
    id: "HEBR-1002",
    label: "HEBR-1002",
    secondaryLabel: "Beginning Hebrew II",
  },
  {
    id: "HEBR-1101",
    label: "HEBR-1101",
    secondaryLabel: "Beginning Biblical Hebrew I",
  },
  {
    id: "HEBR-1102",
    label: "HEBR-1102",
    secondaryLabel: "Beginning Biblical Hebrew II",
  },
  {
    id: "HEBR-3011",
    label: "HEBR-3011",
    secondaryLabel: "Intermediate Hebrew",
  },
  {
    id: "HEBR-3012",
    label: "HEBR-3012",
    secondaryLabel: "Intermediate Hebrew II",
  },
  { id: "HEBR-3993", label: "HEBR-3993", secondaryLabel: "Directed Studies" },
  {
    id: "HEBR-4001",
    label: "HEBR-4001",
    secondaryLabel: "Beg Hebrew I for Grad Research",
  },
  {
    id: "HEBR-4002",
    label: "HEBR-4002",
    secondaryLabel: "Beg Hebrew II Grad Research",
  },
  {
    id: "HEBR-4011",
    label: "HEBR-4011",
    secondaryLabel: "Intermediate Hebrew I Grad Res",
  },
  {
    id: "HEBR-4012",
    label: "HEBR-4012",
    secondaryLabel: "Intermediate Hebrew II GradRes",
  },
  {
    id: "HEBR-4104",
    label: "HEBR-4104",
    secondaryLabel: "Beg Bib Hebrew I Grad Res",
  },
  {
    id: "HEBR-4105",
    label: "HEBR-4105",
    secondaryLabel: "Beg Bib Hebrew II Grad Res",
  },
  {
    id: "HEBR-5090",
    label: "HEBR-5090",
    secondaryLabel: "Advanced Modern Hebrew",
  },
  {
    id: "HEBR-5200",
    label: "HEBR-5200",
    secondaryLabel: "Advanced Classical Hebrew",
  },
  {
    id: "HEBR-5506",
    label: "HEBR-5506",
    secondaryLabel: "Adv. Heb II Israeli Mossad",
  },
  {
    id: "HEBR-5515",
    label: "HEBR-5515",
    secondaryLabel: "Adv. Heb II Mod. Israel",
  },
  { id: "HEBR-5992", label: "HEBR-5992", secondaryLabel: "Directed Readings" },
  {
    id: "HIST-1011W",
    label: "HIST-1011W",
    secondaryLabel: "Civilization & the Environment",
  },
  { id: "HIST-1082", label: "HIST-1082", secondaryLabel: "Jesus in History" },
  {
    id: "HIST-1365",
    label: "HIST-1365",
    secondaryLabel: "Global Tourism & Environment",
  },
  {
    id: "HIST-1534",
    label: "HIST-1534",
    secondaryLabel: "Intro Jewish History & Culture",
  },
  {
    id: "HIST-3000",
    label: "HIST-3000",
    secondaryLabel: "New Topics in History",
  },
  { id: "HIST-3001", label: "HIST-3001", secondaryLabel: "Public History" },
  {
    id: "HIST-3023",
    label: "HIST-3023",
    secondaryLabel: "Hands-On History: Seminar",
  },
  {
    id: "HIST-3061",
    label: "HIST-3061",
    secondaryLabel: "Spectacles in Antiquity",
  },
  {
    id: "HIST-3066",
    label: "HIST-3066",
    secondaryLabel: "Pathways to Civilization",
  },
  {
    id: "HIST-3067W",
    label: "HIST-3067W",
    secondaryLabel: "Arch. of Prehistoric Europe",
  },
  { id: "HIST-3092", label: "HIST-3092", secondaryLabel: "Jesus in History" },
  { id: "HIST-3415", label: "HIST-3415", secondaryLabel: "Global Migrations" },
  { id: "HIST-3432", label: "HIST-3432", secondaryLabel: "Modern Africa" },
  {
    id: "HIST-3435",
    label: "HIST-3435",
    secondaryLabel: "Hist of South Africa from 1910",
  },
  {
    id: "HIST-3456",
    label: "HIST-3456",
    secondaryLabel: "Soc Mvts in African Diaspora",
  },
  {
    id: "HIST-3493",
    label: "HIST-3493",
    secondaryLabel: "Islam: Religion and Culture",
  },
  {
    id: "HIST-3502W",
    label: "HIST-3502W",
    secondaryLabel: "Anc Israel: Conquest to Exile",
  },
  { id: "HIST-3518", label: "HIST-3518", secondaryLabel: "Jewish Humor" },
  {
    id: "HIST-3534",
    label: "HIST-3534",
    secondaryLabel: "Intro Jewish History & Culture",
  },
  { id: "HIST-3767", label: "HIST-3767", secondaryLabel: "Eastern Orthodoxy" },
  {
    id: "HIST-3856",
    label: "HIST-3856",
    secondaryLabel: "Civil Rights & Black Power Mvt",
  },
  {
    id: "HIST-3865",
    label: "HIST-3865",
    secondaryLabel: "African Am Hist 1865-Present",
  },
  {
    id: "HIST-3868W",
    label: "HIST-3868W",
    secondaryLabel: "Race and War in America",
  },
  {
    id: "HIST-3871",
    label: "HIST-3871",
    secondaryLabel: "Amer Indians to 1830",
  },
  {
    id: "HIST-3876",
    label: "HIST-3876",
    secondaryLabel: "Asian Americans and Food",
  },
  {
    id: "HIST-3877",
    label: "HIST-3877",
    secondaryLabel: "Asian Amer. History",
  },
  {
    id: "HIST-4970",
    label: "HIST-4970",
    secondaryLabel: "History Day Mentorship",
  },
  {
    id: "HIST-5051",
    label: "HIST-5051",
    secondaryLabel: "Mesopotamian Historiography",
  },
  { id: "HIST-8122", label: "HIST-8122", secondaryLabel: "Public Histories" },
  { id: "HIST-8960", label: "HIST-8960", secondaryLabel: "Topics in History" },
  {
    id: "HMED-3055",
    label: "HMED-3055",
    secondaryLabel: "Women, Health, and History",
  },
  {
    id: "HMED-3940",
    label: "HMED-3940",
    secondaryLabel: "Topics in History of Medicine",
  },
  { id: "HSCI-8125", label: "HSCI-8125", secondaryLabel: "Sci. Revolution" },
  {
    id: "HSEM-3231H",
    label: "HSEM-3231H",
    secondaryLabel: "Queer and Feminist Hip Hop",
  },
  {
    id: "HSEM-3248H",
    label: "HSEM-3248H",
    secondaryLabel: "Conspiracy Theories",
  },
  {
    id: "HSPH-8001",
    label: "HSPH-8001",
    secondaryLabel: "Who Owns the Past? Pub History",
  },
  {
    id: "HSPH-8002",
    label: "HSPH-8002",
    secondaryLabel: "Core Practices Heritage Study",
  },
  {
    id: "HSPH-8003",
    label: "HSPH-8003",
    secondaryLabel: "Race & Indigeneity in Hrtg Rep",
  },
  { id: "HSPH-8004", label: "HSPH-8004", secondaryLabel: "Capstone in HSPH" },
  {
    id: "HSPH-8005",
    label: "HSPH-8005",
    secondaryLabel: "Leadership&Future of Hist Orgs",
  },
  { id: "HSPH-8101", label: "HSPH-8101", secondaryLabel: "Internship" },
  {
    id: "HSPH-8992",
    label: "HSPH-8992",
    secondaryLabel: "Directed Readings in HSPH",
  },
  {
    id: "JWST-1034",
    label: "JWST-1034",
    secondaryLabel: "Intro Jewish History & Culture",
  },
  { id: "JWST-1201", label: "JWST-1201", secondaryLabel: "Bible: Context" },
  { id: "JWST-1205", label: "JWST-1205", secondaryLabel: "The Bible and Film" },
  {
    id: "JWST-3013W",
    label: "JWST-3013W",
    secondaryLabel: "Biblical Law & Jewish Ethics",
  },
  {
    id: "JWST-3034",
    label: "JWST-3034",
    secondaryLabel: "Intro Jewish History & Culture",
  },
  { id: "JWST-3201", label: "JWST-3201", secondaryLabel: "Bible: Context" },
  {
    id: "JWST-3205",
    label: "JWST-3205",
    secondaryLabel: "Women, Gender, & Hebrew Bible",
  },
  {
    id: "JWST-3206",
    label: "JWST-3206",
    secondaryLabel: "Purity and Pollution",
  },
  {
    id: "JWST-3502W",
    label: "JWST-3502W",
    secondaryLabel: "Anc Israel: Conquest to Exile",
  },
  {
    id: "JWST-3506",
    label: "JWST-3506",
    secondaryLabel: "\tThe Israeli Mossad",
  },
  {
    id: "JWST-3515",
    label: "JWST-3515",
    secondaryLabel: "Multiculturalism in Israel",
  },
  { id: "JWST-3518", label: "JWST-3518", secondaryLabel: "Jewish Humor" },
  { id: "JWST-3633", label: "JWST-3633", secondaryLabel: "The Holocaust" },
  {
    id: "JWST-3896",
    label: "JWST-3896",
    secondaryLabel: "Jewish Studies Internship",
  },
  { id: "JWST-4000W", label: "JWST-4000W", secondaryLabel: "Final Project" },
  { id: "JWST-4001W", label: "JWST-4001W", secondaryLabel: "Final Project" },
  {
    id: "JWST-5013W",
    label: "JWST-5013W",
    secondaryLabel: "Biblical Law & Jewish Ethics",
  },
  {
    id: "LANG-2012",
    label: "LANG-2012",
    secondaryLabel: "Accelerated Catalan II",
  },
  {
    id: "LANG-2361",
    label: "LANG-2361",
    secondaryLabel: "Intermediate Biblical Hebrew I",
  },
  {
    id: "LANG-2381",
    label: "LANG-2381",
    secondaryLabel: " Intermediate Marathi I",
  },
  {
    id: "LANG-3014",
    label: "LANG-3014",
    secondaryLabel: " Reading Catalan for Research",
  },
  {
    id: "LANG-3062",
    label: "LANG-3062",
    secondaryLabel: "Advanced Persian II",
  },
  {
    id: "LANG-3235",
    label: "LANG-3235",
    secondaryLabel: "Adv Hebrew:  Popular Culture",
  },
  {
    id: "LANG-3401",
    label: "LANG-3401",
    secondaryLabel: "Regional Cultures of Brazil",
  },
  {
    id: "LANG-5125",
    label: "LANG-5125",
    secondaryLabel: "Adv Vietnamese Translation I",
  },
  {
    id: "LANG-5361",
    label: "LANG-5361",
    secondaryLabel: "Intermediate Biblical Hebrew I",
  },
  { id: "LAT-1001", label: "LAT-1001", secondaryLabel: "Beg. Latin I" },
  { id: "LAT-1002", label: "LAT-1002", secondaryLabel: "Beg. Latin II" },
  {
    id: "LAT-2001",
    label: "LAT-2001",
    secondaryLabel: "Intermediate Latin Prose",
  },
  {
    id: "LAT-2002",
    label: "LAT-2002",
    secondaryLabel: "Intermediate Latin Poetry",
  },
  {
    id: "LAT-3003",
    label: "LAT-3003",
    secondaryLabel: "Intermediate Latin Prose",
  },
  {
    id: "LAT-3004",
    label: "LAT-3004",
    secondaryLabel: "Intermediate Latin Poetry",
  },
  { id: "LAT-3993", label: "LAT-3993", secondaryLabel: "Directed Studies" },
  { id: "LAT-4001", label: "LAT-4001", secondaryLabel: "Beginning Latin I" },
  {
    id: "LAT-5003",
    label: "LAT-5003",
    secondaryLabel: "Int Latin Prose: Grad Research",
  },
  {
    id: "LAT-5004",
    label: "LAT-5004",
    secondaryLabel: "Int Latin Poetry Grad Research",
  },
  { id: "LAT-5100", label: "LAT-5100", secondaryLabel: "Advanced Reading" },
  {
    id: "LAT-5200",
    label: "LAT-5200",
    secondaryLabel: "Adv Reading Later Latin",
  },
  { id: "LAT-5701", label: "LAT-5701", secondaryLabel: "Lat Prose Comp" },
  { id: "LAT-5993", label: "LAT-5993", secondaryLabel: "Directed Studies" },
  {
    id: "LAT-8200",
    label: "LAT-8200",
    secondaryLabel: "Readings in Latin Verse",
  },
  { id: "LAT-8910", label: "LAT-8910", secondaryLabel: "Seminar" },
  {
    id: "LAW-6058",
    label: "LAW-6058",
    secondaryLabel: "Human Rights Advocacy",
  },
  {
    id: "LAW-6637",
    label: "LAW-6637",
    secondaryLabel: "Business and Human Rights",
  },
  {
    id: "LAW-6879",
    label: "LAW-6879",
    secondaryLabel: "Poverty and Human Rights",
  },
  {
    id: "LAW-6916",
    label: "LAW-6916",
    secondaryLabel: "Biblical Law and Jewish Ethics",
  },
  {
    id: "LGTT-5110",
    label: "LGTT-5110",
    secondaryLabel: "Tech & Second Lang Classroom",
  },
  {
    id: "LGTT-5111",
    label: "LGTT-5111",
    secondaryLabel: "The Web for Language Learning",
  },
  {
    id: "MEST-3206",
    label: "MEST-3206",
    secondaryLabel: "Purity and Pollution",
  },
  { id: "MEST-3993", label: "MEST-3993", secondaryLabel: "Directed Studies" },
  {
    id: "MEST-4043",
    label: "MEST-4043",
    secondaryLabel: "Archaeology of Northern Europe",
  },
  { id: "MEST-5993", label: "MEST-5993", secondaryLabel: "Directed Studies" },
  {
    id: "MIMS-8001",
    label: "MIMS-8001",
    secondaryLabel: "Theories of the Moving Image",
  },
  {
    id: "MIMS-8003",
    label: "MIMS-8003",
    secondaryLabel: "Historiography of Moving Image",
  },
  { id: "MUS-3301", label: "MUS-3301", secondaryLabel: "Black American Music" },
  {
    id: "OLPD-5011",
    label: "OLPD-5011",
    secondaryLabel: "Leading Organizational Change",
  },
  {
    id: "OLPD-5056",
    label: "OLPD-5056",
    secondaryLabel: "Case Studies - Policy Research",
  },
  {
    id: "OLPD-5061",
    label: "OLPD-5061",
    secondaryLabel: "Ethnographic Research Methods",
  },
  { id: "OLPD-5095", label: "OLPD-5095", secondaryLabel: "Problems: OLPD" },
  {
    id: "OLPD-5128",
    label: "OLPD-5128",
    secondaryLabel: "Anthropology of Education",
  },
  {
    id: "OLPD-5364",
    label: "OLPD-5364",
    secondaryLabel: "Context/Practice Ed Leadership",
  },
  { id: "OLPD-8015", label: "OLPD-8015", secondaryLabel: "Inquiry strategies" },
  { id: "OLPD-8095", label: "OLPD-8095", secondaryLabel: "Problems: OLPD" },
  {
    id: "PA-5490",
    label: "PA-5490",
    secondaryLabel: "Topics in Social Policy",
  },
  {
    id: "PHIL-1004W",
    label: "PHIL-1004W",
    secondaryLabel: "Intro to Political Philosophy",
  },
  {
    id: "POL-3135",
    label: "POL-3135",
    secondaryLabel: "Political Dynam Horn of Afric",
  },
  {
    id: "POL-3478W",
    label: "POL-3478W",
    secondaryLabel: "Contemporary African Politics",
  },
  {
    id: "PUBH-7091",
    label: "PUBH-7091",
    secondaryLabel: "Independent Study: CHP",
  },
  {
    id: "PUBH-7475",
    label: "PUBH-7475",
    secondaryLabel: "Stat Learning & Data Mining",
  },
  { id: "PUBH-8401", label: "PUBH-8401", secondaryLabel: "Linear Models" },
  {
    id: "PUBH-8475",
    label: "PUBH-8475",
    secondaryLabel: "Stat Learning & Data Mining",
  },
  {
    id: "RELS-1001",
    label: "RELS-1001",
    secondaryLabel: "Intro: Religions of the World",
  },
  {
    id: "RELS-1002",
    label: "RELS-1002",
    secondaryLabel: "Introduction to Religion",
  },
  {
    id: "RELS-1034",
    label: "RELS-1034",
    secondaryLabel: "Intro Jewish History & Culture",
  },
  { id: "RELS-1082", label: "RELS-1082", secondaryLabel: "Jesus in History" },
  { id: "RELS-1201", label: "RELS-1201", secondaryLabel: "Bible: Context" },
  {
    id: "RELS-1203",
    label: "RELS-1203",
    secondaryLabel: "Bible: New Testament",
  },
  { id: "RELS-1205", label: "RELS-1205", secondaryLabel: "The Bible and Film" },
  {
    id: "RELS-3001W",
    label: "RELS-3001W",
    secondaryLabel: "Theory and Method in Religion",
  },
  {
    id: "RELS-3013W",
    label: "RELS-3013W",
    secondaryLabel: "Biblical Law & Jewish Ethics",
  },
  {
    id: "RELS-3034",
    label: "RELS-3034",
    secondaryLabel: "Intro Jewish History & Culture",
  },
  {
    id: "RELS-3070",
    label: "RELS-3070",
    secondaryLabel: "Topics in Religious Studies",
  },
  {
    id: "RELS-3071",
    label: "RELS-3071",
    secondaryLabel: "Greek & Hellenistic Religions",
  },
  { id: "RELS-3076", label: "RELS-3076", secondaryLabel: "The Apostle Paul" },
  { id: "RELS-3092", label: "RELS-3092", secondaryLabel: "Jesus in History" },
  { id: "RELS-3201", label: "RELS-3201", secondaryLabel: "Bible: Context" },
  {
    id: "RELS-3205",
    label: "RELS-3205",
    secondaryLabel: "Women, Gender, & Hebrew Bible",
  },
  {
    id: "RELS-3206",
    label: "RELS-3206",
    secondaryLabel: "Purity and Pollution",
  },
  {
    id: "RELS-3213",
    label: "RELS-3213",
    secondaryLabel: "Bible: New Testament",
  },
  {
    id: "RELS-3321",
    label: "RELS-3321",
    secondaryLabel: "American Indian Philosophies",
  },
  {
    id: "RELS-3502W",
    label: "RELS-3502W",
    secondaryLabel: "Anc Israel: Conquest to Exile",
  },
  {
    id: "RELS-3535",
    label: "RELS-3535",
    secondaryLabel: "Death and Afterlife",
  },
  { id: "RELS-3611", label: "RELS-3611", secondaryLabel: "Eastern Orthodoxy" },
  {
    id: "RELS-3626W",
    label: "RELS-3626W",
    secondaryLabel: "Witches, Seers, and Saints",
  },
  {
    id: "RELS-3627",
    label: "RELS-3627",
    secondaryLabel: "End of World Lit & History",
  },
  { id: "RELS-3631", label: "RELS-3631", secondaryLabel: "Islam in America" },
  {
    id: "RELS-3704",
    label: "RELS-3704",
    secondaryLabel: "Exploring the Quran",
  },
  {
    id: "RELS-3712",
    label: "RELS-3712",
    secondaryLabel: "Islam: Religion and Culture",
  },
  {
    id: "RELS-3716",
    label: "RELS-3716",
    secondaryLabel: "Gender in the Islamic World",
  },
  {
    id: "RELS-3896",
    label: "RELS-3896",
    secondaryLabel: "Internship for Academic Credit",
  },
  { id: "RELS-3993", label: "RELS-3993", secondaryLabel: "Directed Studies" },
  {
    id: "RELS-4049",
    label: "RELS-4049",
    secondaryLabel: "Religion and Culture",
  },
  { id: "RELS-4952", label: "RELS-4952", secondaryLabel: "Capstone" },
  {
    id: "RELS-4993",
    label: "RELS-4993",
    secondaryLabel: "Capstone: Directed Study",
  },
  {
    id: "RELS-5001",
    label: "RELS-5001",
    secondaryLabel: "Theory and Method in Religion",
  },
  {
    id: "RELS-5013W",
    label: "RELS-5013W",
    secondaryLabel: "Biblical Law & Jewish Ethics",
  },
  {
    id: "RELS-5071",
    label: "RELS-5071",
    secondaryLabel: "Greek & Hellenistic Religions",
  },
  { id: "RELS-5993", label: "RELS-5993", secondaryLabel: "Directed Studies" },
  {
    id: "RELS-8070",
    label: "RELS-8070",
    secondaryLabel: "Readings in Religious Texts",
  },
  {
    id: "RELS-8190",
    label: "RELS-8190",
    secondaryLabel: "Seminar in Religions Antiquity",
  },
  {
    id: "SCMC-1201V",
    label: "SCMC-1201V",
    secondaryLabel: "Honors Course: Cinema",
  },
  { id: "SCMC-1201W", label: "SCMC-1201W", secondaryLabel: "Cinema" },
  {
    id: "SCMC-1202W",
    label: "SCMC-1202W",
    secondaryLabel: "Media: Word, Image, Sound",
  },
  {
    id: "SCMC-3001W",
    label: "SCMC-3001W",
    secondaryLabel: "Hist of Cinema & Media Culture",
  },
  {
    id: "SCMC-3201",
    label: "SCMC-3201",
    secondaryLabel: "Digital Filmmaking I",
  },
  {
    id: "SCMC-3202",
    label: "SCMC-3202",
    secondaryLabel: "Digital Filmmaking II",
  },
  {
    id: "SCMC-3210",
    label: "SCMC-3210",
    secondaryLabel: "Cinema and Ideology",
  },
  {
    id: "SCMC-3211",
    label: "SCMC-3211",
    secondaryLabel: "Global & Transnational Cinemas",
  },
  {
    id: "SCMC-3212W",
    label: "SCMC-3212W",
    secondaryLabel: "Documentary Cinema",
  },
  { id: "SCMC-3220W", label: "SCMC-3220W", secondaryLabel: "Screen Cultures" },
  { id: "SCMC-3221", label: "SCMC-3221", secondaryLabel: "On Television" },
  {
    id: "SCMC-3896",
    label: "SCMC-3896",
    secondaryLabel: "Internship for Academic Credit",
  },
  { id: "SCMC-3993", label: "SCMC-3993", secondaryLabel: "Directed Study" },
  { id: "SCMC-4993", label: "SCMC-4993", secondaryLabel: "Directed Study" },
  {
    id: "SCMC-5001",
    label: "SCMC-5001",
    secondaryLabel: "Debates Cinema/Media Culture",
  },
  {
    id: "SCMC-5002",
    label: "SCMC-5002",
    secondaryLabel: "Advanced Film Analysis",
  },
  { id: "SCMC-5303", label: "SCMC-5303", secondaryLabel: "Sound Studies" },
  { id: "SCMC-5993", label: "SCMC-5993", secondaryLabel: "Directed Study" },
  { id: "SLAV-3900", label: "SLAV-3900", secondaryLabel: "Topics in Slavic" },
  { id: "SLAV-5900", label: "SLAV-5900", secondaryLabel: "Topics in Slavic" },
  { id: "SMLI-1221", label: "SMLI-1221", secondaryLabel: "Beginning Somali" },
  { id: "SMLI-1222", label: "SMLI-1222", secondaryLabel: "Somali II" },
  {
    id: "SMLI-1225",
    label: "SMLI-1225",
    secondaryLabel: "Accelerated Beginning Somali I",
  },
  {
    id: "SMLI-1226",
    label: "SMLI-1226",
    secondaryLabel: "Accelerated Beg Somali II",
  },
  {
    id: "SMLI-3226",
    label: "SMLI-3226",
    secondaryLabel: "Accelerated Beg Somali II",
  },
  {
    id: "SMLI-3227",
    label: "SMLI-3227",
    secondaryLabel: "Intermediate Somali I",
  },
  {
    id: "SMLI-3228",
    label: "SMLI-3228",
    secondaryLabel: "Intermediate Somali II",
  },
  {
    id: "SMLI-4227",
    label: "SMLI-4227",
    secondaryLabel: "Int Somali Grad Research I",
  },
  {
    id: "SMLI-4228",
    label: "SMLI-4228",
    secondaryLabel: "Int Somali Grad Research II",
  },
  { id: "SOC-3207", label: "SOC-3207", secondaryLabel: "Global Islamophobia" },
  {
    id: "SOC-3211W",
    label: "SOC-3211W",
    secondaryLabel: "Race and Racism in the US",
  },
  {
    id: "SOC-3215",
    label: "SOC-3215",
    secondaryLabel: "Supercapitalism Global Econ",
  },
  { id: "SOC-3225", label: "SOC-3225", secondaryLabel: "The Power of the 1%" },
  {
    id: "SOC-3251W",
    label: "SOC-3251W",
    secondaryLabel: "Race, Class, and Gender",
  },
  {
    id: "SOC-3505",
    label: "SOC-3505",
    secondaryLabel: "Migrations: People in Motion",
  },
  {
    id: "SOC-3613W",
    label: "SOC-3613W",
    secondaryLabel: "The Politics of Eating",
  },
  {
    id: "SOC-3681",
    label: "SOC-3681",
    secondaryLabel: "Gender in the Islamic World",
  },
  { id: "SOC-3701", label: "SOC-3701", secondaryLabel: "Social Theory" },
  {
    id: "SOC-4311",
    label: "SOC-4311",
    secondaryLabel: "Power, Justice & Environment",
  },
  { id: "SOC-4321", label: "SOC-4321", secondaryLabel: "Globalize This!" },
  {
    id: "STAT-1001",
    label: "STAT-1001",
    secondaryLabel: "Intro Ideas of Stat",
  },
  {
    id: "STAT-3011",
    label: "STAT-3011",
    secondaryLabel: "Intro Statistical Analysis",
  },
  { id: "STAT-3021", label: "STAT-3021", secondaryLabel: "Intro to Prob&Stat" },
  { id: "STAT-3022", label: "STAT-3022", secondaryLabel: "Data Analysis" },
  {
    id: "STAT-3032",
    label: "STAT-3032",
    secondaryLabel: "Regression and Correlated Data",
  },
  {
    id: "STAT-3301",
    label: "STAT-3301",
    secondaryLabel: "Regression/Statistical Cmptng",
  },
  {
    id: "STAT-3701",
    label: "STAT-3701",
    secondaryLabel: "Intro to Statistical Computing",
  },
  {
    id: "STAT-4051",
    label: "STAT-4051",
    secondaryLabel: "Applied Statistics I",
  },
  {
    id: "STAT-4052",
    label: "STAT-4052",
    secondaryLabel: "Intro to Statistical Learning",
  },
  {
    id: "STAT-4101",
    label: "STAT-4101",
    secondaryLabel: "Theory of Statistics I",
  },
  {
    id: "STAT-4102",
    label: "STAT-4102",
    secondaryLabel: "Theory of Statistics II",
  },
  {
    id: "STAT-4893W",
    label: "STAT-4893W",
    secondaryLabel: "Communication for Statistician",
  },
  { id: "STAT-5021", label: "STAT-5021", secondaryLabel: "Stat Analysis" },
  {
    id: "STAT-5052",
    label: "STAT-5052",
    secondaryLabel: "Statistical & Machine Learning",
  },
  {
    id: "STAT-5101",
    label: "STAT-5101",
    secondaryLabel: "Theory of Statistics I",
  },
  {
    id: "STAT-5102",
    label: "STAT-5102",
    secondaryLabel: "Theory of Statistics II",
  },
  {
    id: "STAT-5302",
    label: "STAT-5302",
    secondaryLabel: "Applied Regression Analysis",
  },
  {
    id: "STAT-5303",
    label: "STAT-5303",
    secondaryLabel: "Designing Experiments",
  },
  {
    id: "STAT-5401",
    label: "STAT-5401",
    secondaryLabel: "Applied Multivariate Methods",
  },
  {
    id: "STAT-5421",
    label: "STAT-5421",
    secondaryLabel: "Analysis of Categorical Data",
  },
  {
    id: "STAT-5511",
    label: "STAT-5511",
    secondaryLabel: "Time Series Analysis",
  },
  {
    id: "STAT-5601",
    label: "STAT-5601",
    secondaryLabel: "Nonparametric Methods",
  },
  {
    id: "STAT-5701",
    label: "STAT-5701",
    secondaryLabel: "Statistical Computing",
  },
  {
    id: "STAT-5731",
    label: "STAT-5731",
    secondaryLabel: "Bayesian Astrostatistics",
  },
  { id: "STAT-5993", label: "STAT-5993", secondaryLabel: "Tutorial" },
  {
    id: "STAT-8051",
    label: "STAT-8051",
    secondaryLabel: "Advanced Regression Techniques",
  },
  {
    id: "STAT-8052",
    label: "STAT-8052",
    secondaryLabel: "Applied Statistical Methods 2",
  },
  {
    id: "STAT-8053",
    label: "STAT-8053",
    secondaryLabel: "Applied Statistical Methods 3",
  },
  {
    id: "STAT-8054",
    label: "STAT-8054",
    secondaryLabel: "Statistical Methods 4",
  },
  {
    id: "STAT-8056",
    label: "STAT-8056",
    secondaryLabel: "Stat Learning & Data Mining",
  },
  {
    id: "STAT-8101",
    label: "STAT-8101",
    secondaryLabel: "Theory of Statistics 1",
  },
  {
    id: "STAT-8102",
    label: "STAT-8102",
    secondaryLabel: "Theory Statistics 2",
  },
  {
    id: "STAT-8111",
    label: "STAT-8111",
    secondaryLabel: "Mathematical Statistics I",
  },
  { id: "STAT-8112", label: "STAT-8112", secondaryLabel: "Math Stat II" },
  { id: "STAT-8311", label: "STAT-8311", secondaryLabel: "Linear Models" },
  {
    id: "STAT-8313",
    label: "STAT-8313",
    secondaryLabel: "Topics Exper Design",
  },
  { id: "STAT-8511", label: "STAT-8511", secondaryLabel: "Time Series" },
  {
    id: "STAT-8801",
    label: "STAT-8801",
    secondaryLabel: "Statistical Consulting",
  },
  {
    id: "STAT-8821",
    label: "STAT-8821",
    secondaryLabel: "Curricular Practical Training",
  },
  {
    id: "STAT-8888",
    label: "STAT-8888",
    secondaryLabel: "Thesis Credit:Doct*",
  },
  { id: "STAT-8913", label: "STAT-8913", secondaryLabel: "Literature Seminar" },
  {
    id: "STAT-8931",
    label: "STAT-8931",
    secondaryLabel: "Advance Topics Stat",
  },
  {
    id: "STAT-8932",
    label: "STAT-8932",
    secondaryLabel: "Advanced Topics in Statistics",
  },
  {
    id: "STAT-8992",
    label: "STAT-8992",
    secondaryLabel: "Dirctd Rdng & Rsrch",
  },
  {
    id: "SWAH-1221",
    label: "SWAH-1221",
    secondaryLabel: "Beginning Swahili, Semester I",
  },
  {
    id: "SWAH-1222",
    label: "SWAH-1222",
    secondaryLabel: "Beginning Swahili, Semester II",
  },
  {
    id: "SWAH-3225",
    label: "SWAH-3225",
    secondaryLabel: "Intermediate Swahili",
  },
  {
    id: "SWAH-3226",
    label: "SWAH-3226",
    secondaryLabel: "Intermediate Swahili II",
  },
  {
    id: "SWAH-4221",
    label: "SWAH-4221",
    secondaryLabel: "Beg Swahili Grad Research I",
  },
  {
    id: "SWAH-4222",
    label: "SWAH-4222",
    secondaryLabel: "Beg Swahili Grad Research  II",
  },
  {
    id: "SWAH-4225",
    label: "SWAH-4225",
    secondaryLabel: "Inter Swahili Grad Research",
  },
  {
    id: "SWAH-4226",
    label: "SWAH-4226",
    secondaryLabel: "Inter Swahili Grad Research II",
  },
  { id: "WRIT-1301", label: "WRIT-1301", secondaryLabel: "University Writing" },
  {
    id: "WRIT-1301H",
    label: "WRIT-1301H",
    secondaryLabel: "Honors: University Writing",
  },
];
