name: Tests

on: [push, pull_request]

env:
  LDAP_PASSWORD: ${{ secrets.LDAP_PASSWORD }}

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bluesheet_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DB_DATABASE: bluesheet_testing
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: cp .env.example .env

      - name: Setup PHP 8.1 to match server
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - run: composer install --no-progress --prefer-dist --optimize-autoloader

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - run: php artisan key:generate

      - name: Run Laravel Server
        run: php artisan serve --no-reload &

      - name: Run integration tests with Pest
        run: php artisan test

      - name: Run unit tests with Jest
        run: yarn test:unit

      - name: Run E2E tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost"
          browser: chrome
          config: baseUrl=http://localhost

      - name: Upload test screenshots if any
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots

      - name: Upload snapshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-snapshots
          path: cypress/snapshots
